src/gerbil/runtime/gx-gambc#.scm
Make compiler expand path correctly.
=> Change ~~/lib to ~~lib

src/std/crypto/libcrypto.scm, src/std/xml/_libxml.scm
it's just a quick fix, for now.
Maybe somebody can reuse & clean it up.
=> dirty work-around for compilation with gambit --with-cplusplus

src/std/build-spec.ss, src/std/make.ss
=> std build: honor LDFLAGS and CCFLAGS

src/std/net/request.ss
=> std/net/request: fix host header in request redirects

src/std/srfi/19.ss, src/std/srfi/srfi-19.scm
=> srfi-19: stricter make-time, updated leap seconds

src/std/misc/string.ss
Also, remove unexported and now unused macro first-value.
=> Fix package in std/misc/string

src/gerbil/expander/module.ss
=> Set nested module separator to $$

doc/r7rs.md, src/lang/scheme/base-impl.ss, src/lang/scheme/scheme-test.ss
Add some minimal tests.
TODO: hook those tests into some test script.
=> Implement R7RS division operators

src/std/text/json.ss
=> Fix LangSec issue in JSON parser

src/std/generic.ss
=> std/generic: fix generic dispatch; s/class-instace?/class-instance?

doc/stdlib.md, src/std/build-spec.ss, src/std/db/postgresql-driver.ss, src/std/misc/list-test.ss, src/std/misc/list.ss, src/std/misc/repr.ss, src/std/test.ss, src/std/text/csv.ss
Also add with-list-builder macro to std/misc/list
=> Import std/misc/repr from clan/utils/repr

.travis.yml, .travis/install-gambit.sh
Add support for building gerbil and testing its stdlib on travis-ci.
=> ci: setup travis-ci

doc/guide.md
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/vyzo/gerbil/75)
=> Fix some typos.

src/std/misc/list.ss
=> [misc/list] add alist->plist. alist? plist?

src/std/misc/process.ss
The documentation states that
If the check-status?: argument is true, then the process exit status
will be checked, and an error will be raised if it isn't 0.
In fact the argument is named check-status without the question mark
and setting it to '#t' or '#f' results in an error
*** ERROR IN std/misc/process#run-process__% -- Operator is not a
PROCEDURE
Fix this by checking if check-status is true rather than just trying
to call it. This potentially breaks existing code that was using the
undocumented behavior and passing a procedure to be called rather than
a flag.
=> run-process: fix handling of check-status

src/bootstrap/gerbil/expander/root__0.scm, src/bootstrap/gerbil/expander/stxcase__0.scm, src/bootstrap/gerbil/expander/stxcase__1.scm
for changes in expander/root to distinguish bsds.
=> bootstrap update

src/std/build-spec.ss, src/std/make.ss
=> std/build: utilize pkg-config with fallback to custom build env variables

src/std/srfi/13.ss, src/std/srfi/srfi-13.scm
Massages the srfi/13 implementation to use gerbil opt-lambdas and drop
the expensive argument checks that make the library such a beast.
it's now faster and and it compiles much faster.
=> gerbilized srfi/13

doc/tutorial/httpd.md, src/tutorial/httpd/simpled.ss
that's why we have iterators, to make code look pretty.
=> Prettify httpd tutorial: use for loop

src/std/os/signal.ss
=> remove SIGUNUSED, it's deprecated

doc/guide.md
Declaration was spelled declation.
=> Typo fix (documentation)

src/std/os/signal-handler.ss
=> fix g++ compilation issues in MacOS

doc/reference/core-builtin.md
Fills the stubs in `reference/core-builtin.md`.
=> Documentation for runtime builtins

doc/reference/requests.md
Applies documentation to request.md
=> Document request.md

src/std/net/bio/input.ss
=> std/net/bio: add optional need argument to bio-read-subu8vector*

doc/reference/net.md, src/std/net/bio.ss, src/std/net/bio/input.ss
Provides some more input methods for bio buffers:
- bio-read-char
- bio-read-substring, bio-read-string
- bio-read-line
=> More bio input methods

src/std/misc/channel.ss
- channel iterator
- destroy method that closes the channel
=> some niceties for channels

doc/guide/README.md
Add Dockerfile link and corrected docker images tags
=> Add Dockerfile link

doc/reference/core-builtin.md, src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ssxi.ss, src/gerbil/runtime/gx-gambc0.scm
=> Simpler implementation of hash clear

doc/guide/package-manager.md, src/tools/gxpkg.ss
Implements a search command using the gerbil directory.
=> gxpkg search

doc/guide/shell.md
=> quick typo fix

src/gerbil/prelude/core.ss
=> prelude: allow empty bodies in alet*

src/std/ref.ss
- signed integer vectors
- fix signatures for flonum vectors and large integer vectors
=> std/ref: some fixes

src/bootstrap/gerbil/core__5.scm, src/bootstrap/gerbil/gambit/exact__1.scm, src/bootstrap/gerbil/gambit/ports__0.scm, src/bootstrap/gerbil/gambit/threads__0.scm, src/gerbil/prelude/core.ss
=> prelude: fix expansion of definline'd references

src/std/misc/uuid.ss
Also exports the uuid type while at it.
=> equal? for uuids

doc/reference/misc.md, src/std/build-spec.ss, src/std/misc/barrier-test.ss, src/std/misc/barrier.ss, src/std/misc/completion-test.ss, src/std/misc/completion.ss, src/std/run-tests.ss
- Adds a thread barrier abstraction
- Tunes and adds documentation/test for async completions
=> Thread barriers

doc/guide/srfi.md
makes it easier to find documentation.
=> add links to srfi documents in srfi list

CHANGELOG.md, doc/guide/README.md, doc/guide/r7rs.md
=> Release v0.15

.travis/install-gambit.sh, Dockerfile, src/bootstrap/gerbil/compiler/compile__0.scm, src/bootstrap/gerbil/compiler/optimize-ann__0.scm, src/bootstrap/gerbil/compiler/optimize-call__0.scm, src/bootstrap/gerbil/compiler/optimize-top__0.scm, src/bootstrap/gerbil/compiler/optimize-xform__0.scm, src/bootstrap/gerbil/compiler/optimize__0.scm, src/bootstrap/gerbil/core.ssxi.ss, src/bootstrap/gerbil/expander/module__0.scm, src/bootstrap/gerbil/gambit/exact.ssi, src/bootstrap/gerbil/gambit/exact__rt.scm, src/bootstrap/gerbil/gambit/ports__0.scm, src/bootstrap/gerbil/gambit/threads__0.scm, src/gerbil/prelude/core.ssxi.ss, src/gerbil/runtime/gx-gambc0.scm, src/lang/scheme/base-ports.ss, src/lang/scheme/file.ss, src/lang/scheme/inexact-impl.ss, src/lang/scheme/process-context-impl.ss
Gambit v4.9.3 brings more builtin r7rs procedures.
There is also a breaking change in the implementation of promises.
See also #232.
=> Updates for Gambit v4.9.3

src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ssxi.ss
setenv takes one argument to clear a variable and two to set it.
=> prelude: fix setenv airity

src/gerbil/runtime/gx-gambc1.scm
This is a change in gambit post v4.9.3.
=> Update use of ##make-readenv for changes in gambit

doc/reference/net.md, src/std/build-spec.ss, src/std/net/bio.ss, src/std/net/bio/file.ss
Adds buffer implementations for file i/o using raw devices; faster than ports.
=> File raw device buffers

src/gerbil/gxi, src/gerbil/gxi-build-script
- remove `set -u`
- use simple parameter expansion
- proper quoting for GERBIL_HOME
fix #240
=> simplify shell scripts

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss
Nothing fancy, just another utility function.
=> misc: butlast

doc/reference/requests.md
update std/net/request documentation to match documentation template given in #263
=> update std/net/request to match new document template

doc/reference/text.md
Update the text module to use new documentation template.
Still could use some coding examples but I think its ready for review.
=> update std/text to use new doc template

doc/reference/web.md
Update the web.md to use new documentation template and flesh out the documentation while at it.
=> update web.md to use new doc template

doc/reference/core-builtin.md
mechanical doc tweaks to make core builtin use the new documentation template
=> mechanical changes to update builtin to use new doc template

doc/reference/core-prelude.md, src/bootstrap/gerbil/core.ssxi.ss, src/bootstrap/gerbil/gambit/os.ssi, src/gerbil/prelude/core.ssxi.ss, src/gerbil/prelude/gambit/os.ss
Add support for ##tty-mode-reset
=> Add tty mode reset

doc/reference/misc.md, src/std/build-spec.ss, src/std/misc/bytes-test.ss, src/std/misc/bytes.ss, src/std/run-tests.ss
Utils for swapping bytes and reversing bytevectors.
=> New std/misc/bytes module.

Dockerfile
=> Put Gerbil binaries in PATH in the Docker container

doc/reference/misc.md, src/std/misc/bytes-test.ss, src/std/misc/bytes.ss
We previously only had a method that mutated the vector in-place.
=> Add non-destructive u8vector-reverse to std/misc/bytes.

src/gerbil/prelude/core.ss, src/gerbil/runtime/gx-gambc#.scm, src/gerbil/runtime/gx-gambc0.scm, src/gerbil/runtime/gx-gambc1.scm
=> Fix incompatibilities with gambit head

doc/reference/misc.md, src/std/misc/string-test.ss, src/std/misc/string.ss
Nothing special, just a little missing tool.
=> misc/string: string-whitespace?

src/std/misc/bytes.ss
This patch is required for the code to compile with gcc 9.2.0 on freebsd 12.0.
=> use C99 stdint types

doc/guide/r7rs.md, doc/reference/misc.md, doc/reference/text.md
Some typos. Another PR is on its way to make `std/text/utf8` follow the docs.
I think the documentation for `std/text` could be reviewed a little to add some clarity.
=> PR-338 review

doc/reference/text.md
See https://github.com/vyzo/gerbil/pull/352.
=> Update documentation for utf8 encoding and decoding procedures

src/std/os/fdio.ss, src/std/os/flock.ss
Not just raw devices; simplifies programming directly with file descriptors.
=> Allow read/write on raw file descriptors

src/tools/gxprof.ss
=> make gxprof work again

src/gerbil/gxc, src/gerbil/gxi
=> Add -h and -v options to gxi, understand --help in gxc

src/std/os/kqueue.ss
I'm not sure if this is entirely correctly.  Please check.
fix #372
=> std/os/kqueue uses begin-ffi

doc/guide/intro.md
sealing produces really fast code!
=> More documentation for sealed class performance

src/std/iter.ss
Very common operations, so they get optimized expansion in single arm loops.
=> Optimize for loop expansion for in-iota and in-range loops

src/std/iter.ss
Complement to #384
It only optimizes `for` and not `for/collect` and `for/fold` as the latter two are nonsensical; the loop never terminates without a continuation escape.
=> Optimize expansion for in-naturals for loops

src/gerbil/compiler/compile.ss
gambit/gambit#422 rears its ugly head again...
=> Optimize case-lambda dispatch and values check/list conversion

src/std/iter.ss
=> fix iter-input-port bug

README.md, doc/.vuepress/config.js
- In README
- In navbar in cons.io
=> Gitter links

src/std/foreign.ss
=> add typecast for malloc to work with c++ compilers

src/std/misc/repr.ss
This PR does 3 things:
- Extends `:std/misc/repr` print-representation to print multiple values as `(values v ...)` instead of `(begin0 #8 "#<unknown>")`.
- Extends `display-separated` with an optional keyword argument `separate-prefix?:`, a boolean to determine whether to separate the prefix from the first element if it exists.
- Uses the new `display-separated` argument in printing things like `values`, `vector`, and structs. This includes changing printing of empty vectors from `(vector )` to `(vector)`, and empty structs from `(foo )` to `(foo)`.
=> Improve repr for values, separate-prefix?

src/gerbil/runtime/gx-gambc0.scm
=> Use ##file-exists? instead of ##os-file-info

.gitignore, doc/reference/core-prelude.md, src/bootstrap/gerbil/core.ssi, src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ss, src/gerbil/prelude/core.ssxi.ss
Did I miss something? I've also added `src/TAGS` to `.gitignore`.
=> String >uninterned symbol

src/std/srfi/128.ss
=> fix vector comparator

doc/reference/core-prelude.md, src/gerbil/prelude/core.ss, src/gerbil/runtime/gx-gambc0.scm, src/std/make.ss, src/std/srfi/srfi-19.scm
Small fixes to std/make and std/srfi/19.
=> Small fixes

doc/guide/env-vars.md, doc/reference/make.md, doc/reference/misc.md, src/gerbil/compiler/driver.ss, src/gerbil/runtime/build.scm, src/lang/build-deps, src/lang/build.ss, src/std/build-deps, src/std/build-spec.ss, src/std/build-std.ss, src/std/build.ss, src/std/make.ss, src/std/misc/concurrent-plan.ss, src/std/misc/list.ss, src/std/misc/pqueue.ss, src/std/stxparam.ss, src/std/stxutil.ss
=> Parallelize the build of stdlib, to a point

src/build/build0.scm, src/build/build1.ss, src/gerbil/runtime/build-lib.scm, src/gerbil/runtime/build.scm
Stage 1 is still largely unparallelized, except for the part shared with stage0.
=> Parallelize stage0

src/std/make.ss, src/std/misc/concurrent-plan.ss
=> Use ##cpu-count instead of reinventing it badly

src/std/test.ss
Also use defrule where appropriate
=> std/test: allow computed name in test-case

src/gerbil/compiler/driver.ss, src/install
=> Updated Gambit UTF8 options

doc/guide/README.md
is this correct @eraserhd @ober ? AFAIU we don't need those any more.
=> remove obsolete variable definitions for homebrew installation

doc/reference/core-prelude.md, src/gerbil/prelude/core.ss
=> make def support curried definitions

doc/guide/README.md, doc/guide/emacs.md, etc/gerbil-mode.el
Did I miss something or added too much?
=> gerbil-mode: improve highlighting and indentation

doc/reference/core-prelude.md, doc/reference/misc.md, doc/reference/ref.md, doc/reference/sort.md, doc/reference/sugar.md
A bunch of examples and minor documentation improvements.
=> More documentation and examples

src/std/build-deps, src/std/text/csv-test.ss, src/std/text/csv.ss
Fix bug with cr? and lf? being reversed.
Merge all options in one structure for nice speed-up.
Add tests for all those parameters.
=> CSV parsing improvements

src/build.sh
=> Add a sanity check at the beginning of build.sh

src/tutorial/lang/scuby-etc.ss
=> Update scuby-etc.ss w/minor spelling correction.

doc/reference/misc.md
=> fix misc doc rendering

src/gerbil/runtime/gx-gambc0.scm
=> added fixnum check to first argument of make-list

doc/tutorials/httpd.md
Happy to revise these instructions if something is amiss or another formatting approach is preferred
=> httpd nginx deployment example

doc/reference/db.md
=> Add reference doc for Connection Pools

src/std/db/postgresql-driver.ss
=> handle parameter status responses in postgres

Dockerfile, etc/gambit-docker/Dockerfile
Updated versions of packages
v4.9.4 and v0.17
=> Update Gerbil & Gambit Dockerfiles

src/std/text/utf8-test.ss, src/std/text/utf8.ss
Fixes https://github.com/vyzo/gerbil/issues/687.
=> Fix segfault in utf8 decoding and encoding

src/gerbil/gxc
=> Fix incorrect comment in gxc help message

doc/reference/sort.md, src/std/build-deps, src/std/misc/symbol.ss
=> Issue 709: caching symbolic comparison functions

src/std/build-deps, src/std/build-spec.ss, src/std/crypto.ss, src/std/crypto/etc.ss, src/std/crypto/kdf.ss, src/std/crypto/libcrypto.ss
so that we can have nice key derivation.
=> crypto: add support for KDFs and scrypt

docker/Dockerfile
Add features new in Gambit. 4.9.5 
Use makefiles for build/install.
=> Fix docker builds

src/std/build-deps, src/std/build-spec.ss, src/std/interface-benchmark.ss, src/std/interface.ss
- optimize the hell out of casting
- make satisfies? more intelligent
- check if there is a prototype
- optimistically create a prototype if all methods resolve, as the satisfies? test is likely to be followed by a cast
=> std/interface: dramatically improve casting performance and make satisfies? more intelligent

src/misc/http-perf/baseline.ss, src/misc/http-perf/hellod.ss, src/std/build-deps, src/std/build-spec.ss, src/std/net/httpd/file.ss, src/std/net/httpd/handler.ss, src/std/net/httpd/server.ss
Currently on top of #728; will rebase on master once that merges.
See #724.
As the title suggests, httpd has been adjusted to use stdio; that was painless.
=> Use stdio in httpd

etc/gerbil-mode.el
=> gerbil-mode: add interface indentation

docker/Makefile
Allow arm64, and x86_64 docker images under :latest.
=> Improve docker multi arch

src/std/amb.ss
This was prompted when I noticed a segfault in a CI run; it's been difficult to reproduce, but the culprit was identified as the amb implementation. After successive changes, I have arrived at an implemtantation that doesn't crash and also have much cleaner behavior.
Changes:
- run amb in a separate thread, using a clean state environment; this is automatically handled by begin-amb
- ditch parameters and use thread-specficic state; no need to be thrashing the dynamic environment for this when all we want to do is set a thread specific state variable.
- use continuations more effectively.
=> amb: rewrite internals

README.md, doc/guide/README.md, doc/guide/build.md, doc/guide/emacs.md, doc/guide/env-vars.md, doc/guide/getting-started.md, doc/guide/intro.md, doc/guide/macos.md, doc/guide/package-manager.md, doc/guide/profiler.md, doc/guide/r7rs.md, doc/guide/shell.md, doc/reference/test.md, install.sh, src/build.sh
This concludes our trip to the future; it is now present!
Closes #726
=> Welcome to the Future, Part III

doc/guide/getting-started.md
Another quickie, a custom box was missing its tip.
=> fix missing tip for custom box

configure
=> Fix it so it builds when CFLAGS/LDFLAGS are set by user

doc/guide/intro.md
General cleanup in the introduction.
=> Some Guide updates

README.md
we shouldn't send people to an extinct network...
=> README: freenode is dead; long live gitter!

doc/guide/README.md, doc/guide/build.md, doc/guide/env-vars.md, doc/guide/getting-started.md, doc/guide/intro.md
Doing a general editorial pass in the guide.
=> Documentation: Editorial Fixes

configure
no need to pull in a detached head
=> configure: git fetch gambit

src/std/misc/template-test.ss, src/std/misc/template.ss
So that we can emit bash scripts easily.
=> Add escape character to string templates

src/std/net/ssl/libssl.ss
See https://github.com/openssl/openssl/issues/12707
=> Fix libssl deprecation

src/tools/gxprof.ss
This adds support for analysis mode, including callgraphs. It is an acceptable tool at this point.
Closes #736
=> show gxprof some love

README.md, doc/.vuepress/config.js, doc/guide/README.md, doc/guide/docker.md, doc/guide/emacs.md, doc/guide/getting-started.md, doc/guide/intro.md, doc/guide/package-manager.md, doc/reference/dev/ffi.md, doc/reference/std/db/postgres.md, doc/reference/std/stxparam.md, doc/tutorials/ensemble.md, doc/tutorials/httpd.md, doc/tutorials/kvstore.md, doc/tutorials/languages.md, doc/tutorials/proxy.md
it is mighty-gerbils/gerbil now!
=> Fix repo links

.github/workflows/ci.yml, configure
Pin gambit to 24201248effa23d5017be4992b5b9879e4cd3a4c
Important fix affecting Gerbil, wrt compilation of letrec*.
See https://github.com/gambit/gambit/issues/659
=> Update gambit pin

.github/workflows/docker-image.yml, docker/Makefile, src/std/db/leveldb.ss
=> fix docker build

doc/reference/srfi/README.md, src/srfi/212.ss, src/srfi/build.ss, src/std/build-spec.ss, src/std/srfi/212.ss
=> Add support for SRFI 212

doc/guide/r7rs.md, src/std/srfi/124.ss
Closes #696 
The implementation is on par with gambit's implementation.
cc @dpk
=> Improve ephemeron implementation, update the doc notice

README.md, doc/.vuepress/config.js, doc/reference/dev/README.md, doc/reference/dev/bach.md, doc/reference/dev/debug.md, doc/reference/dev/optimizing.md
Section on optimizing tips is the new entrant.
Closes #665
=> Documentation improvements

src/std/misc/decimal.ss, src/std/misc/number.ss
Improve integer-log, implement more general factor-out-powers.
=> Small improvements to number and decimal modules

src/std/net/request.ss
Problem was between keyboard and chair; fixed.
Fixes #893
=> Fix issue 893

src/std/source-test.ss, src/std/source.ss, src/std/stxutil.ss
=> Fix :std/source

Makefile, install.sh
DESTDIR is always put before the actual prefix, so simplify the logic.
=> fix DESTDIR, pass it on via "make install" 

doc/reference/std/misc/repr.md, src/std/misc/alist.ss, src/std/misc/plist.ss, src/std/misc/repr-test.ss, src/std/misc/repr.ss
Fix bugs, better handle unrepresentable case, add tests.
=> Fix std/misc/repr

src/tools/gxtags.ss
Discrimination on the basis of religion is unconstitutional :)
=> support vim TAGS

src/std/net/socks/server.ss
the intention is to not allow proxied connections to localhost, as this is a security issue. We also need to do it for DOMAINNAME addresses too or an attacker can just ask to connecto to "localhost".
:facepalm:
=> fix issue in socks server

src/std/net/socks/server.ss
Ok, that previous fix half fixed it... because ipv6 local net is 0 prefixed.
=> Fix socks server some more

doc/.vuepress/config.js, doc/reference/std/misc/decimal.md, src/std/build-spec.ss, src/std/misc/decimal-test.ss, src/std/misc/decimal.ss, src/std/text/char-set.ss
Also fix build-spec for srfi 141, and a typo in char-set.
=> Documentation, tests and bug fixes for std/misc/decimal

README.md, doc/guide/env-vars.md, doc/guide/intro.md
Also fixes some issues with the intro guide.
=> Add MacOS installation instructions in the top level README

doc/reference/gerbil/runtime/hash-tables.md, doc/reference/gerbil/runtime/special-objects.md, doc/reference/std/net/socks.md, doc/reference/std/source.md, doc/reference/std/sugar.md, src/gerbil/runtime/util.ss
- Removes some stale documentation
- Improves the implementation of make-symbol, make-keyword, and as-string
- Fixes stray or missing :::'s from docs
=> Some small fixes

src/gerbil/gxc-main.ss, src/gerbil/gxi-main.ss, src/gerbil/main.ss
observed: when redirecting to a file, the output wasn't flushed.
=> force output from gerbil binary

homebrew/README.org, homebrew/gerbil-scheme.rb
=> Change homebrew to point to working commit. Still rev 0 :)

.gitignore, CHANGELOG.md, README.md, doc/guide/README.md, homebrew/README.org, homebrew/gerbil-scheme.rb, src/gerbil/runtime/version.ss
Waiting for some automation from @ober; other than that ready to go!
=> Release v0.18

homebrew/README.org, homebrew/gerbil-scheme.rb, install.sh
get rid of the dependency on GNU find
=> use find the POSIX way

homebrew/README.org, homebrew/gerbil-scheme.rb
Now that we have fixed the `find` issue I added the correct commit so homebrew works. I also indented the ruby file to look better.
=> Update homebrew git revision and bump formula revision: 1

doc/reference/gerbil/expander/identifiers.md
Based on vyzo's answer in gitter
=> Adds stx-identifier docs

doc/.vuepress/public/img/gerbil-detailed-consio_OPT.svg, doc/.vuepress/public/img/gerbil-detailed_INK.svg, doc/.vuepress/public/img/gerbil-detailed_OPT.svg, doc/.vuepress/public/img/gerbil-flat-colored-consio_OPT.svg, doc/.vuepress/public/img/gerbil-flat-colored_INK.svg, doc/.vuepress/public/img/gerbil-flat-colored_OPT.svg, doc/package.json, etc/gerbil-mode.el
This PR updates old repository links to new ones.
=> Update repository links

homebrew/README.org, homebrew/gerbil-scheme.rb
Points to the previous commit that _should_ be near 0.18.1.
=> Update Homebrew Formula for 0.18.1

doc/guide/getting-started.md
=> Fix typos in getting started

src/std/interface.ss
=> fix identifier bug in interface macro

src/std/net/request.ss
Try to add request-text to error message on failed request.
=> Quick fix #1146

src/tools/gxhttpd-test.ss, src/tools/gxhttpd.ss
add a preserve? thunk that can avoid cache invalidation for handlers and files that have not been modified.
=> improve gxhttpd cache intelligence

src/tutorial/httpd/build.ss
=> tutorial/httpd build optimized on Darwin

src/gerbil/compiler/driver.ss
Shut linker up when duplicate options.
=> Linker verbose

CONTRIBUTING.md, doc/package.json
- Adds a script to run local doc server with `npm run dev`
- Adds CONTRIBUTING.md
=> CONTRIBUTING.md

doc/guide/emacs.md
As promised in the Matrix group, I have added documentation on how to setup Gerbil in Doom emacs.
Let me know in Matrix if any other documents need to be updated. Happy to help. I love this project.
=> Update Emacs docs with Doom Emacs setup.

src/gerbil/runtime/c3.ss, src/gerbil/runtime/mop.ss, src/gerbil/test/c3-test.ss, src/gerbil/test/mop-test.ss
- Slight refactor of C3, check eq? for list equality
- Fix handling of opaque? flag for classes and equality of fields
- Protect write-style from requiring every indirect user having to use gambit-includesharp
=> MOP tweaks

docker/Makefile
Some cleanup of variable names.
=> 1231: Add dependencies for Gerbil package for ubuntu/fedora.

src/std/build-spec.ss, src/std/ide/interface.ss, src/std/ide/model.ss
interface and data model for now.
=> IDE: IDEServer interface

src/build/build-bach.ss, src/build/build-libgerbil.ss, src/gerbil/compiler/driver.ss
1) gsc crashes when compiling stuff with debug options: https://github.com/gambit/gambit/issues/953
2) netbsd apparently needs -lutil for bach
=> BSD issues

doc/reference/dev/bootstrap.md, doc/reference/gerbil/runtime/c3.md, src/bootstrap/gerbil/runtime/c3~0.scm, src/gerbil/runtime/c3.ss, src/gerbil/runtime/util.ss, src/gerbil/test/c3-test.ss
Bug fix and documentation update for C4
Fix a bug in merge-sis! failing to
properly handle non-simultaneous null? cases. Add tests and documentation.
=> C4 Linearization improvements and documentation

doc/reference/gerbil/core/expression.md
This PR updates the documentation for the main conditionals constructs provided by Gerbil: cond, case, and, or, ?, when, unless
=> Documentation for main conditionals macro
