src/build.sh, src/build0.sh, src/build1.sh, src/build2.sh, src/build2_fini.sh, src/build_stdlib.sh, src/gerbil/gxi
1- Use /bin/sh not /bin/bash so it will work on NixOS
(and hopefully also BSD and any minimalist Unix distributions).
2- Use options -eu to fail early on any error, and
to count undefined variables as errors.
=> Tweak wrapper shell scripts

src/std/crypto/libcrypto.scm, src/std/crypto/libcrypto.ssi
Hello,
this PR should close issue #9. Code compiles cleanly now, but i haven't tested it otherwise.
Is there a testsuite covering libcrypto ffi anywhere (directly or otherwise)?
EVP_dss1 is no longer available under OpenSSL-1.1.x.  This is what the Manpage for OpenSSL-1.0.0
has to say:
> EVP_dss() and EVP_dss1() return EVP_MD structures for SHA and SHA1 digest algorithms but using DSS ( DSA ) for the signature algorithm. Note: there is no need to use these pseudo-digests in OpenSSL 1.0.0 and later, they are however retained for compatibility. 
So i've chosen to remove that function from the library entirely.
Works for you?
=> libcrypto ffi: compatibility with openssl-1.1.x; EVP_dss1 exists no longer

src/std/text/json.ss
This saves a few bytes in what isn't human-readable anyway.
Use a pretty printer if you want to extract human-readable text from it.
=> Omit spaces when writing JSON

doc/core-prelude.md
=> Fix tyo in doc/core-prelude

src/std/build-spec.ss, src/std/make.ss
Per @edw comments in #18, it is preferable for the variable to be called `CPPFLAGS` as documented by the various package management tools.
In the principle of least surprise, use the same variable.
=> be consistent with package management tools: it's CPPFLAGS.

src/std/srfi/srfi-19.scm
Some functions used wrong parameter order — one by me, and one by a patch pre-import.
=> srfi-19: fix breakage wrt make-time

src/std/misc/string.ss
Add functions to cut a prefix from a string, just like we have for a suffix.
=> std/misc/string: string-{trim,split}-prefix

src/std/os/fcntl.ss
O_DSYNC not supported on freebsd fnctl
=> remove O_DSYNC not in FreeBSD 11

src/std/srfi/43.ss, src/std/srfi/srfi-43.scm
I never finished this patch.
@vyzo what did you say was the correct approach to fixing the conflicts between SRFI 43 and the prelude (including inherited Gambit symbols) ?
=> Fix symbol conflicts in SRFI 43

etc/gerbil.el
You want a new *scheme* process, even though your current process may be
unresponsive? No problem: with C-x 9, there you get a new one.
=> C-x 9 for restart-scheme

src/lang/scheme/time-impl.ss, src/std/text/_zlib.scm
Got some minor errors when compiling with g++ compiler on macOS.
1. (void *) return must be cast in c++.
2. Cant jump (GOTO) place in between declaration and definition. Split it.
=> Fix c++ compilation.

doc/guide.md
`parse-html` is a symbol defined in `:std/xml/libxml` 
(not `:std/xml`)
=> Doc example fix

doc/stdlib.md, src/gerbil/expander/root.ss, src/std/build-spec.ss, src/std/net/socket/kqueue-server.ss, src/std/net/socket/server.ss, src/std/os/kqueue.ss
Greetings. I noticed that there were bindings to the linux epoll syscall in `std` and thought that it might be good to have some for the similar kqueue system on BSD.
I do not yet fully understand how the underlying IO mechanism works wihtin the Gambit layers, but I was able to get something working by following what was going on in `epoll.ss` and `epoll-server.ss`, changing what needed to be changed.
I tested this by making some socket servers as well as running a modified version of the `httpd-test` that starts up the socket server. I'd be happy to test further or commit some tests targeting the socket interface (I didn't see any) if desired.
=> Add bindings to kqueue and kqueue-based socket server

src/std/srfi/41.ss
While playing around with srfi-41 I realized that `stream-of` was missing from its export list. And to make the interface of the stream type complete I also added the `stream?` predicate.
=> std/srfi/41: add missing exports

src/gerbil/expander/root.ss, src/std/os/kqueue.ss
std/os/kqueue did not compile on OS X. The implementations of kqueue on the various BSDs share a common base but vary in the details. I disabled the missing parts on OS X by using `cond-expand`. Therefore I introduced another level of cond-expand features which distinguishes between the different BSDs. This might also be useful for future compatibility issues.
=> std/os/kqueue: make compilaton work on darwin

src/std/net/socket/kqueue-server.ss
wait-out must be enabled only when the socket is open for output.
also, error in case of bad direction.
=> fix bug in kqueue-server socket constructor

src/std/net/socket/epoll-server.ss, src/std/net/socket/kqueue-server.ss, src/std/os/epoll.ss, src/std/os/fcntl.ss, src/std/os/fdio.ss, src/std/os/kqueue.ss, src/std/os/pipe.ss, src/std/os/socket.ss
The file descriptors created by epoll and kqueue are set to nonblocking (and closeonexec).
Also extends fcntl to have a combined operation for the two flags, and uses it accordintly.
=> Nonblock poll

src/std/net/socket/kqueue-server.ss, src/std/net/socket/server-test.ss, src/std/os/kqueue.ss, src/std/run-tests.ss
Closes #89.
Created a simple echo server for testing epoll or kqueue-based socket
servers, provide that the test script is run on linux or BSD,
respectively. Happy to add additional tests before merging if there
are any suggestions.
I wasn't quite sure of the best way to make use of cond-expand to take
care of the system-dependent aspects of these tests, so definitely
open to advice here, as well.
Tested on linux and OpenBSD.
=> Add tests for socket server

doc/stdlib.md, src/std/net/socket/kqueue-server.ss, src/std/os/kqueue.ss
Request for comments.
I kept the convenience functions per @vyzo, and exported the lower level `kevent` wrapper, and the `timespec` constructor in case `kevent` callers want to set their own timeouts. I also created a `kevent-set!` function that essentially wraps the `EV_SET` C macro and made use of it where possible.
=> Export low-level kqueue functions, use in kqueue socket server

src/bootstrap/gerbil/compiler/driver__0.scm, src/bootstrap/gerbil/expander/root__0.scm, src/bootstrap/gerbil/expander/stxcase__0.scm, src/bootstrap/gerbil/expander/stxcase__1.scm, src/gerbil/compiler/driver.ss
The bug manifested with this error when building a package with a binary:
```
*** ERROR IN gxc#compile-exe-stub-module -- No such file or directory
(with-output-to-file "~/.gerbil/bin/gxpkgd.scm" '#<procedure #40>)
```
Also updates the bootstrap, which includes the updated bsd feature bindings.
=> Bug fix: compiler should create output binary directory

src/std/net/request.ss
http-get bombs when it sees an empty header; for example:
```
> (http-get "https://raw.githubusercontent.com/vyzo/gerbil-simsub/master/gerbil.pkg")
*** ERROR IN std/net/request#http-request -- http-request-read-response!: [io-error] Malformed header
--- irritants: #<input-output-port #10 (tcp-client "raw.githubusercontent.com" 443)> X-Geo-Block-List: 
```
This fixes the header rx to accept empty headers, which appear as empty strings.
=> admit empty headers in http responses

CHANGELOG.md, README.md, doc/guide/README.md
- Update the README to not duplicate documentation from the guide, where the installation instructions now live.
- Stated dependency on Gambit v4.9.0, mostly due to https://github.com/gambit/gambit/issues/352
- CHANGELOG for v0.13
=> Release v0.13 Notes

src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ssxi.ss
The arity declaration of `process-status` is wrong, failing compilation of invocations using the timeout optional parameters.
=> fix arity declaration for process-status

src/build.sh
rsync call in build.sh doesn't seem to needed as same thing can be achieved with simple cp call.
=> replace rsync call with cp

src/build.sh, src/gerbil/gxi, src/gerbil/gxi-build-script
Here's small tweaks to make Gerbil shell scripts work on other shells besides just bash.
Tested with OpenBSD ksh and dash shell.
=> Make shell scripts use more portable constructs

src/std/crypto/libcrypto.scm
HMAC_CTX_init no longer exists...
=> fix libcrypto for openssl v1.1

doc/reference/net.md, src/std/net/bio.ss, src/std/net/bio/buffer.ss, src/std/protobuf/io.ss
Add support for delimited input buffers, which allow us to read delimited values from a buffer without copying.
=> Input Subbuffers

src/std/protobuf/io.ss
- Avoid allocating intermediate buffers in bio-read-delimited-string
- Implement XXXs for port interface
=> Some work in protobuf/io

src/std/net/repl.ss
gambit v4.9.1 considers the escape sequences invalid; unicode it is...
=> std/net/repl: write-u8vector for control codes

src/std/srfi/srfi-1.scm
It's a bug/typo in the original reference implementation.
=> add missing dot in delete-duplicates! signature

src/std/srfi/133.ss, src/std/srfi/134.ss, src/std/srfi/43.ss, src/std/srfi/srfi-133.scm, src/std/srfi/srfi-134.scm, src/std/srfi/srfi-43.scm
A few srfis contained private definitions; pruned and imported srfi/8 instead.
=> std/srfi: clean up redefinitions of receive

Dockerfile
Use copy to push the checkout context to the container. 
Add makeinfo for doc building.
=> use parent copy of gerbil checkout.

doc/reference/misc.md, src/std/build-spec.ss, src/std/misc/deque.ss, src/std/misc/pqueue.ss, src/std/misc/queue.ss
Adds `:std/misc/deque` implementing (imperative) double ended queues.
Also normalizes the queue pop interface in `:std/misc/queue` and `:std/misc/pqueue` for an optional default value.
=> Double Ended Queues

src/std/build-spec.ss, src/std/srfi/121-iter.ss, src/std/srfi/127-iter.ss, src/std/srfi/41-iter.ss, src/std/srfi/41.ss
Adds support for iterating over srfi sequence types
- std/srfi/41-iter: lazy streams -- `in-stream`, generic `:iter` on stream type
- std/srfi/121-iter: generators -- `in-generator`
- std/srfi/127-iter: lseqs -- `in-lseq`
=> iterators for srfis

src/bootstrap/gerbil/core.ssi, src/gerbil/prelude/core.ss
It was missing; and it's very useful for cond-expand compile time evaluation.
=> prelude: define system-version

doc/reference/misc.md, src/std/misc/rbtree.ss
It is expected constant time, with lexicographic ordering only in case of hash collisions.
=> rbtree: symbol-hash-cmp for hash based symbol ordering

src/bootstrap/gerbil/expander/compile__0.scm, src/bootstrap/gerbil/expander/core.ssi, src/bootstrap/gerbil/expander/core__0.scm, src/bootstrap/gerbil/expander/core__1.scm, src/bootstrap/gerbil/expander/module__0.scm, src/bootstrap/gerbil/expander/module__1.scm, src/bootstrap/gerbil/expander/root__0.scm, src/bootstrap/gerbil/expander/stxcase__0.scm, src/bootstrap/gerbil/expander/stxcase__1.scm, src/bootstrap/gerbil/expander/top__0.scm, src/gerbil/expander/core.ss
Dynamic repls (like treadmill) need to rebind within module context, hence this parameter.
=> Adds an expander parameter to control rebinding

doc/guide/intro.md, doc/reference/coroutine.md, src/std/coroutine-test.ss, src/std/coroutine.ss, src/std/iter.ss, src/std/run-tests.ss
Reinstates the old implementation of coroutines as cothreads.
The salient advantage is that cothreads can yield within finalizer blocks, as they don't swap continuations.
=> Cothread: heavyweight coroutine threads

src/gerbil/interactive/init.ss, src/std/build-spec.ss, src/std/interactive.ss
so that they are available to import in development environments like treadmill.
=> refactor interactive utilities out of interactive/init.ss

doc/reference/misc.md, src/std/misc/lru.ss
- Normalize the LRU cache interface to be compatible with hash tables and rbtrees
- Add documentation for LRU caches.
=> LRU caches: normalize interface and documentation

src/std/make.ss
BUG: gsc-compile was placing foreign compilation artifacts under std instead of the prefix.
=> std/make: fix foreign compilation prefix

doc/.vuepress/config.js, doc/guide/ffi.md, doc/reference/foreign.md, etc/gerbil.el, src/std/actor/xdr.ss, src/std/build-spec.ss, src/std/foreign.ss, src/std/net/httpd/handler.ss, src/std/os/epoll.ss, src/std/os/error.ss, src/std/os/fcntl.ss, src/std/os/fdio.ss, src/std/os/inotify.ss, src/std/os/pid.ss, src/std/os/pipe.ss, src/std/os/signal.ss, src/std/os/signalfd.ss, src/std/protobuf/io.ss
Adds a `begin-ffi` macro in `:std/foreign`, which simplifies writing foreign stubs.
The macro is used as following:
```
(begin-ffi (id ...) body ...)
```
It expands to an `extern` declaration for ids, and a `begin-foreign` where the body:
- contains a namespace declaration for the extern identifiers
- defines the common macros `define-c-lambda`, `define-guard`, `define-const`, and `define-const*`
- defines the `U8_DATA` and `U8_LEN` preprocessors macros
- defines a proper `ffi_free` procedure for foreign type release functions
=> begin-ffi macro

doc/reference/core-builtin.md, src/bootstrap/gerbil/compiler/optimize-top__0.scm, src/bootstrap/gerbil/expander/module__0.scm, src/gerbil/compiler/optimize-top.ss, src/gerbil/expander/module.ss, src/gerbil/runtime/gx-gambc0.scm, src/std/net/sasl.ss, src/std/protobuf/proto.ss, src/tools/gxpkg.ss
The arguments were reversed, which leads to confusion and potential bugs when importing srfi/13 in code that was already using `string-prefix?`.
Also fixes a bug in gxpkg discovered when auditing usages of `string-prefix?`: package update only accepted github as package provider.
=> Modify string-prefix? argument order to match srfi-13

doc/reference/net.md, src/std/db/postgresql-driver.ss, src/std/net/sasl-test.ss, src/std/net/sasl.ss
More appropriate names, as this is the client api. 
That way, a server-side api can be added with the similar structure.
=> sasl: rename client methods consuming server messages

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss, src/std/run-tests.ss
Little macro to cut a bit of boilerplate code that is often present in name-let loops.
=> when-list-or-empty helper macro

.gitignore, doc/build.sh, src/gerbil/runtime/gx-version.scm
The documentation build is failing because of a broken dependency.
See https://github.com/vuejs/vue-cli/issues/3407
=> Fix vuepress bug

doc/reference/misc.md, src/std/misc/string-test.ss, src/std/misc/string.ss
Since the name `string-replace` is already taken in Scheme I had to choose another one – but would like to use it, if it is okay with you. Other alternative names:
- `string-subst`
- `string-change`
But [most common](https://en.wikipedia.org/wiki/Comparison_of_programming_languages_(string_functions)#replace) is `string-replace`.
=> misc - string-substitute

src/std/net/bio/file.ss, src/std/net/socket/buffer.ss
- Set sentinel methods for closed file buffers, so that we don't crash on use after close
- Mark socket input buffers as final
=> some buffer trivia

doc/reference/core-prelude.md, src/gerbil/prelude/core.ss
This macro was concocted on irc, after chickendan suggested better ergonomics for imports.
You can do
```
(import (group-in :std/misc queue rbtree))
```
and it is equivalent to
```
(import :std/misc/queue :std/misc/rbtree)
```
Nesting also works:
```
(import (group-in :std (misc queue rbtree) (net bio)))
```
=> group-in: A little import macro that reduces import boilerplate

etc/gerbil.el
This seems to fix the following error I got when trying to use [rainbow-delimiter](https://github.com/Fanael/rainbow-delimiters) with `gerbil-mode`:
```
Error during redisplay: (jit-lock-function 1) signaled (void-variable paren-face)
Error during redisplay: (jit-lock-function 501) signaled (void-variable paren-face)
Error during redisplay: (jit-lock-function 1001) signaled (void-variable paren-face)
```
=> Quote paren-face in gerbil.el

doc/reference/core-prelude.md, src/gerbil/prelude/core.ss
It's vexing to have to write `(group-in :std/srfi |1| |2| |3|)` instead of `(group-in :std/srfi 1 2 3)`.
=> Allow numbers in group-in components

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss
Adding rassoc which is similar to the regular assoc func, but compares cdr instead of car. Allows searching for 2nd pair element (with eqv? as default predicate in this case): `(rassoc 2 '((a . 1) (b . 2) (c . 3))) => (b . 2)`
Inspiration came from rassoc in common lisp: http://clhs.lisp.se/Body/f_rassoc.htm
Furthermore, what do you think about the doc styling? Am I free to apply this style to other undocumented std functions as well?
=> Add rassoc function to std/misc/list

src/std/misc/list-test.ss, src/std/misc/list.ss
slight implementation change so that `(when-list-or-empty 10  10)` is longer expands to `10`, but `[]` instead. Docs and name suggest that expansion only happens when input param is a non-empty list.
=> fix: when-list-or-empty documentation and name doesn't match impl

doc/reference/misc.md
std/misc/list:
- style overhaul: call and return syntax block, description, example code block
- example code for each function in that module
- function docs were added or extended
=> doc: overhaul std/misc/list documentation, adding example code

src/std/misc/uuid.ss
`(uuid->string (string->uuid "52e1c499-a964-49f1-16cc-583f417eb62f"))` fails right now, because regex captures four single groups.
While we are at it: change regex so that it allows the whole range of hex chars, but discards other alphabet chars.
=> fix std/misc/uuid#string->uuid and confine regex to hex vals

doc/reference/misc.md
Changed the following regarding docs:
- added a documentation skeleton template
- module imports in code block
- more code examples and descriptions to `shuffle`, `func`, `string`, `timeout`, `uuid`
- some markdown fixes in `list`
=> doc: a few smaller additions to std/misc documentation

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss
Some `slice` functions in other languages take as second parameter an optional index. But I like the limit approach more, since it boils down to take-n-elements. The other possible change to this function is that it could take a negative index as first parameter and therefor make the `slice-right` function unnecessary. Again, I like the explicit nature of `slice-right` and think that not too much functionality should be packed into one function.
=> misc: add slice procedure

doc/reference/misc.md
all submodules in the std/misc reference were overhauled:
- additional descriptions: some fixed, some enriched by reusing gambit's and gerbil's source code comments, some completely fresh
- examples code (some not quite that clever, just trying to get the idea across and show basic usage)
- unified function signature and paramater descriptions
Now, destroy!
=> doc: more std/misc reference overhauling

src/std/misc/repr.ss
`display-element` procedure is set to `d` which only takes a single arg, but
`display-serarated`'s body provides two. One could also add another optional port to
`d`, same as with `p`, but simply using the default port specified in
`display-separated`'s signature solves it as well.
=> fix: error when trying to print u8vector representation

doc/guide/README.md
Fix gxi failing with:
*** ERROR IN ##main -- No such file or directory
(load "/usr/local/lib/gxi-init")
in Homebrew 2.1.6 MacOS 10.14.5
=> Update MacOS homebrew $PATH instructions

src/gerbil/runtime/build.scm
In some cases (such building from a shallow clone created with `git clone --depth=1`) the command `git describe --tags` can fail. And then the `gx-version.scm` file is not created and then the whole build fails. Adding an `--always` parameter allows to continue the build.
=> do not break when git cannot find any tags

doc/reference/misc.md
Needlessly repetitive keyword syntax in documented function signature, which makes it hard to read. Changed the doc template in #263 accordingly.
- Previously: `[separator: separator = #\newline]`
- Now, only name plus colon: `[separator: #\newline]`
- versus optionals, which are declared with an equal sign: `[separator = #\newline]`
=> doc: shorten function keyword syntax in misc.md

etc/gerbil.el
subseq is not defined on emacs 26.2 by default so use seq-subseq instead. This
is defined in seq.el and workes without additional require statements.
I'm not sure about backwards compatibility of using seq.el regarding older emacs versions.
Fixes #278
=> use seq-subseq in gerbil-send-string function

doc/reference/xml.md
Use new document template for xml.md.
I think I got the most of functions correct but few clarifications could be added:
- what are the differences between print-sxml->html, print-sxml->html* and print-sxml->http-fast. Looks to me that html version skips indent, html* indents the result but html-fast also skips indent. So what are the difference between html* and html-fast versions?
=> Doc overhaul for xml.md

src/build/build0.scm
This makes a full build possible with $GERBIL_GSC override.
=> Support $GERBIL_GSC in build0.scm

doc/reference/core-builtin.md
No more `Language does not exist schem` error.
=> Fixed typos in core builtins documentation.

src/std/format.ss
A byte can be represented by 2 characters. Until now a leading character
was 0, it wasn't printed. The new function prepends the string by the correct
amount of 0's to properly display hex values.
Ex:
```
> (printf "~x~n" 2)
02
> (printf "~x~n" 255)
ff
> (printf "~x~n" 256)
0100
```
=> Hex (~x,~X) formatter now pads with #\0.

doc/reference/misc.md, src/std/misc/bytes-test.ss, src/std/misc/bytes.ss
Added a `delim` string parameter to `u8vector->bytestring`. I am still not sure if I want to use strings or chars. Note that `bytestring->u8vector` only accepts a character as delimiter. These functions should be allowed to cancel each other, which is currently not generally the case. It works well for my current needs.
New `u8vector->uint` function. There is a `guard` parameter to prevent runaway execution on vectors of length > 8. Setting `guard` to `#f` allows to compute large uints.
I have run some small benchmarks here: https://gist.github.com/belmarca/75360c45a61d450f29c5f85c1a9e0f58. It appears the function in the current PR is the fastest.
=> New u8vector->uint function, delimiter param to u8vector->bytestring.

src/std/iter-test.ss, src/std/iter.ss
This PR fixes https://github.com/vyzo/gerbil/issues/296.
However I believe this warrants a somewhat larger discussion about error handling/type checking.
First of all, this is an explicit run-time type check. From my limited understanding, this code will be compiled as-is. I.e. Gambit will handle types on its own and then at run-time the `in-range` function will do its own type checking - always. Can we structure the code such that the run-time check is performed at compile-time by gambit?
Secondly, is there a cleaner/simpler way to add such checks to functions?
Lastly, these checks could be used in a lot of different places in the code. Is it desirable to do so or should we let the programmer handle it?
I am asking these questions as a somewhat naive Scheme programmer.
=> Raise an error when in-range arguments are not integers.

doc/.vuepress/config.js, doc/reference/stxutil.md, src/std/build-spec.ss, src/std/stxutil.ss
New module, `:std/stxutil`.
Just `format-id` for now, but we expect it to grow.
=> Standard syntax utilities

doc/reference/iterators.md, src/std/iter-test.ss, src/std/iter.ss
this patch matches racket's behaviour, so no negative step inference in case of `(in-range 5 3)`.
Note: `(for (x (in-range 3 5 -1)) (displayln x))` no longer loops indefinitely.
=> fix: in-range not handling negative stepping

src/lang/scheme/r7rs.ss
This allows library module ids to include numbers.
=> fix issue in r7rs prelude

src/std/generic/macros.ss
I submit this pull request in hope that some small good may come of my triggering the syntax error. :grin:
=> Fix misspelled word in error message.

Dockerfile
In the current `gerbil/scheme` container:
```
/root
/root/gerbil/bin/gxpkg
*** ERROR IN _gx#load-runtime! -- Cannot determine GERBIL_HOME
Error: Missing command
Usage: gxpkg  <command> command-arg ...
```
Not sure whether or not this has to do with changing PATH a few days ago in PR #317. But by setting GERBIL_HOME explicitly, things work.
=> Set GERBIL_HOME in Docker

src/std/actor/proto.ss, src/std/crypto/cipher.ss, src/std/crypto/digest.ss, src/std/generic/macros.ss, src/std/os/socket.ss, src/std/parser/deflexer.ss, src/std/parser/defparser.ss, src/std/protobuf/macros.ss, src/std/protobuf/proto.ss, src/std/srfi/9.ss
This PR cleans up #318 which had refactored `stx-identifier` in `std/make` and `std/build-config`. These need to have local imports and will thus not import `std/stxutil`.
=> Refactor stdlib to use format-id instead of stx-identifier.

src/build.sh
We can now run `./build.sh doc` to generate the documentation locally.
=> Build documentation from build.sh script.

src/gerbil/compiler/driver.ss
this to avoid ovewriting source code that uses the .scm exension.
Fixes #315
=> compiler: use .scmx extension for executable stubs 

doc/guide/intro.md, doc/reference/core-prelude.md, src/gerbil/expander/module.ss
This allows you to import relative to a library using the dot notation.
Within a library `:A/B/C`, an import of ~`.D`~ `./D` will resolve to `:A/B/D`.
=> Relative library module import paths

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss
Inspired by Haskells [group](https://downloads.haskell.org/~ghc/latest/docs/html/libraries/base-4.13.0.0/Data-List.html#v:group) and [groupBy](https://hackage.haskell.org/package/groupBy-0.1.0.0/docs/Data-List-GroupBy.html) function.
=> misc/list: group

doc/guide/intro.md, src/lang/build.ss, src/lang/gerbil/polydactyl.ss
`:gerbil/polydactyl` is a new custom language prelude that treats square brackets as plain parentheses; the language is otherwise the same as `:gerbil/core`.
To use it:
```
#lang :gerbil/polydactyl
;; ... code ...
```
=> polydactyl gerbil

src/std/os/_socket.scm
Everything else compiles.
fix #250
=> skip multicast sourcing socket on NetBSD

src/tools/gxtags.ss
How about just return 1 if locat is not a vector?
fix #286
=> gxtags: correctly handle non-locat positions

doc/guide/intro.md, src/gerbil/runtime/gx-gambc.scm
You can now do `gxi --lang polydactyl` and it will hook the stdin/console readtables to use polydactyl parentheses.
=> Polydactyl as a first class language in gxi

doc/reference/os.md, src/std/build-spec.ss, src/std/os/fcntl.ss, src/std/os/fd.ss, src/std/os/fdio.ss, src/std/os/flock.ss
Adds flock to the `:std/os` package, which exposes the `flock` call and a utility procedure for opening input and output files with locks.
=> Advisory File Locking

src/std/build-spec.ss, src/std/os/flock.ss
This is a supplement to #358; when opening a file with an advisory lock, closing the port will also unlock the file descriptor.
=> unlock ports created with lock on close-port

src/build.sh
The build scripts use defbuild-script now, which builds in `$GERBIL_PATH`; when unset
this defaults to `~/.gerbil/lib`, which is absolutely the wrong place to build.
=> fix issues with building languages and r7rs-large

src/std/net/bio/file.ss
it was ignoring the bytes object and using the buffer...
=> std/net/bio/file: fix bug in file-output-write

src/std/net/bio/file.ss, src/std/os/fdio.ss
- expose a proper `close` in `:std/os/fdio`
- allow raw file descriptors in file bio buffers
=> More file descriptor io support

src/std/sort/lmsort.scm, src/std/sort/sort-support.scm
Helper macros were using it instead of let-values, which showed up in profile samples.
=> don't use call-with-values in sort

doc/guide/ffi.md, doc/reference/foreign.md, src/std/foreign.ss, src/std/os/_socket.scm, src/std/os/epoll.ss, src/std/os/fcntl.ss, src/std/os/fdio.ss, src/std/os/flock.ss, src/std/os/inotify.ss, src/std/os/kqueue.ss, src/std/os/pipe.ss, src/std/os/signal.ss, src/std/os/signalfd.ss
- The macro is now part of the `begin-ffi` macros
- Accessing `errno` is done with inline C instead of an ffi wrapper.
=> Clean up code duplication related to define-with-errno

doc/reference/misc.md, src/std/misc/list-test.ss, src/std/misc/list.ss
Added the `limit` option and fixed a bug about `split` not ordering the sub-lists correctly.
=> misc/list: add 'limit' argument to split procedure

src/gerbil/runtime/gx-gambc.scm
So that import failures result in an actionable error message.
Fixes #312.
=> runtime: hook the display exception hook before trying to import any modules

doc/reference/misc.md, src/std/misc/string-test.ss, src/std/misc/string.ss
The reason why I limited the characters to regex word boundary is because they can easily be typed on any keyboard and are file system friendly. Also there are no "evil characters" that might do something unexpected in a file path when a string generated by the procedure is used in a bash script.
I'll add the documentation when we have an agreement on the scope of `random-string`.
=> Add random-string to misc/string

doc/reference/sugar.md, src/std/sugar.ss
This adds `with-methods`, and its variants `with-class-methods` and `with-class-method` to complement `using`.
They define local names for methods of an object (class) without binding the object.
The difference from `using` is that because the methods are not bound, you have to pass the receiver as first argument.
The advantage over `using` is that there is no implicit allocation from the closure application.
=> Better sugar for local method binding

doc/guide/intro.md, src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ssxi.ss
This inlines `call-method` to avoid the intermediate allocations for apply; results in significant performance improvements for method calling.
Also updates the numbers for class sealing performance for the latest optimizations.
=> Optimize call-method

src/bootstrap/gerbil/core.ssxi.ss, src/gerbil/prelude/core.ssxi.ss, src/gerbil/runtime/gx-gambc0.scm
The procedure families `rem*`, `assget*`, and `pget*` have been specialized to inline the parametric function.
Also of note, `remove` has lost the optional argument -- use `remf` instead.
=> Some runtime optimizations

src/std/net/httpd/handler.ss, src/std/net/socket/buffer.ss
Uses a pool of input and output buffers instead of allocating a new one for each request.
Adds some 2K requests/s in the `ab` benchmark in my laptop.
=> Some httpd optimizations

src/gerbil/runtime/gx-gambc0.scm
Properly process the plist; previously it used mem{q,v,ber} which might erroneously discover a key in a value.
=> improve the pget* family of functions

src/tools/gxpkg.ss
=> gxpkg: create GERBIL_PATH/lib/static if it doesn't exist

src/gerbil/runtime/gx-gambc0.scm, src/std/make.ss
Also optimizes `create-directory*` to check for existence of the target before traversing the hierarchy.
=> Create target directories in make

doc/reference/httpd.md, src/misc/http-perf/hellod.ss, src/std/net/httpd.ss, src/std/net/httpd/mux.ss, src/std/net/httpd/server.ss
- Adds a `static-http-mux` to the available httpd multiplexers; this one takes a static hash table and uses no mutex; it doesn't allow dynamic handler registration.
- Updates the httpd documentation to the new standard
- Updates the httpd perf benchmark program in `src/misc/http-perf` to use the static mux, which sends it over 35K requests/s in my laptop (up from about 34.3K).
=> Static mux for httpd

src/std/net/httpd/handler.ss
- uses a token buffer instead of consing characters in `read-token`.
- improves the title-casing to avoid unnecessary string sets.
- implements buffer management for smp, using a mutex.
=> Some more httpd bumming

etc/gerbil.el
Hi there!
This adds a package header to `gerbil.el` so it can be installed with package managers, and also it replaces the global keybinding for restarting scheme to one specific of scheme buffers and shell (the key is still the same but it's not global anymore).
=> Add package header and replace global keybinding in Gerbil.el

etc/gerbil.el
After byte-compiling `gerbil.el` I realized that an error was triggered due to `lexical-binding`.
This pull request fixes the error, removes all the warnings and some unused code, so that it works as before 😃
=> Gerbil.el - Lexical-binding fixes and improvements

src/std/iter.ss
Optimizes the finalization of iterators:
- inlines `iter-fini!` to avoid cross-module calls in dynamically compiled modules
- replaces the default finalizer with `#f`, to avoid dispatching a useless procedure.
=> Some iterator optimizations

doc/guide/shell.md, src/std/interactive.ss
Introduces procedural forms for macro expansion, `macro-expand` and `macro-expand1`, and expands `@expand` and `@expand1` to use them.
This avoids internal expansion, which has interesting side-effects -- eg it breaks for macros that use `syntax-local-introduce`.
=> avoid internal expansion in @expand and @expand1

src/std/text/json.ss
This adds a `(not safe)` declaration to the json module; also uses `exact-integer?` where appropriate.
The declaration makes it parse almost 3x faster: tested with a 70M ndjson file, runtime was reduced from 8s to 3.1s in my laptop.
=> json: go fast please!

src/gerbil/runtime/gx-gambc.scm, src/std/build-script.ss, src/std/make.ss
- Adds a seperate static-debug: option to `make`, so that default `defbuild-script` options do not bloat binary size and compilation time.
- Adds a `with-cons-load-path` primitive to `gx-gambc`, so that dependencies can be generated without affecting the load path of compilation.
- Uses `with-cons-load-path` in dependency generation in `defbuild-script`.
cc @ober
=> Build system improvements

src/std/make.ss
Helps users locate their binaries.
=> make: print full binary path when compiling executables

src/std/generic/dispatch.ss, src/std/generic/macros.ss
This unrolls the apply by specializing dispatch for generic methods of up to 3 arguments.
It results to a great speed up as there is no allocation for application any more.
The trivial `(:ref vec 1)` test, repeated 10M times, went from `1.88s` to `0.25s` in my laptop.
=> generic dispatch: unroll apply for generic methods of up to 3 arguments

src/std/generic/dispatch.ss, src/std/generic/macros.ss
- disables interrupts in unrolled hash look ups.
- defines unrolled method specializations for 4 arguments.
=> Some more generic tuning

doc/guide/ffi.md, doc/reference/foreign.md, src/std/build-spec.ss, src/std/foreign-test.ss, src/std/foreign.ss, src/std/run-tests.ss
this generates commonly used methods that are used to work with
the c structs
* malloc, setters, getters for struct
* malloc-array, array-ref and array-set! for working with arrays
A compatibility layer is also provided for scheme string types
which is allocated and freed by the generated methods
=> add define-c-struct macro for ffi with c structs

doc/reference/sugar.md, src/std/run-tests.ss, src/std/sugar-test.ss, src/std/sugar.ss
Chain is a macro that reduces left-shifting by adding some syntactic sugar.
I spend a good amount of time thinking about the syntax and the scope of the macro. For example I rejected the idea of a multi-line row body because it would make the macro unreadable. The `with` and `let` variant is there to handle cases where a diamond operator can't be used, e.g. because the variable should be in a nested expression or is intended to be used multiple times.
Example 1:
``` scheme
(import :std/srfi/13)
(chain (string-reverse "hello world")
(string-titlecase <>)
(string-reverse <>))
=> "hellO worlD"
```
Example 2:
``` scheme
(def lst [1 2 3])
(chain lst
([_ . rest] (map number->string rest))  ; with
(v (string-join v ", "))                ; let
(string-append <> " :)"))
=> "2, 3 :)"
```
Example 3: …
=> std/sugar - chain macro

src/std/srfi/159/color.scm
`ansi-escape` function outputs the escape code in smaller pieces,
however `as-unicode` can only recognize ANSI escape code in one
piece. Because of this when you get `col` property from a string with
ANSI escape code it gives incorrect column number.
For reference, see ashinn/chibi-scheme#591. This should fix #429.
=> srfi-159: fix incorrect "col" calculation with ANSI escape codes

doc/reference/core-builtin.md, src/std/build-script.ss, src/std/make.ss
This PR fixes #428 by changing `defbuild-script` to check that the `build-deps` file is up-to-date before using it to compile the project.
In addition to checking `(file-exists? "build-deps")`, it also checks `(file-newer? "build-deps" _)` for the build-script and each source file with deps relevant for making a depgraph.
I have tested this on my machine with the example in #428 and seen that it resolves the issue.
=> Check for out-of-date build-deps

src/std/srfi/srfi-115/regexp.scm
This is a cherry pick from chibi scheme commit 6f281596 (regexp-replace
should respect start/end also for pre/post substitutions, 2019-12-28) by
Alex Shinn.
Chibi tests for 115 now fully pass with this (one test failed before,
the same one added in 6f281596)
=> Fix srfi-115 regexp-replace

doc/reference/format.md, src/std/format.ss, src/std/misc/repr.ss
This PR adds `~r` and `~R` as format specifiers that use `:std/misc/repr`'s `print-representation` function which can use the `:pr` method.
=> Add ~r format specifier for repr

doc/guide/shell.md
I hope that this allows `enter!` and the other Interactive Development Macros to show up in search results from the search bar at the top of [cons.io](cons.io).
=> Add subsections for Interactive Development Macros

doc/reference/core-expander.md
This documents `stx-source` and `stx-wrap-source` in Expander Runtime Utilities.
The documentation for `stx-source` also explains how to access the container, line, and column information, and the documentation for `stx-wrap-source` explains how to construct a locat from the container, line, col, and off information.
=> Document stx-source and stx-wrap-source

src/std/sugar-test.ss, src/std/sugar.ss
Fix an error when using a sub-expression in a chain-diamond context. The below valid code returned previously the error `More than one body expression in chain-variable context`.
``` scheme
(chain (iota 3)
(map (lambda (v) (1+ v)) <>))
```
=> Fix :std/sugar chain macro

doc/reference/misc.md, src/std/misc/ports.ss
Strait forward procedures to save a string or list-of-strings to a file. A newline is added by default to the last line of the file (see [StackExchange](https://unix.stackexchange.com/a/18789) for why). This allows for easier future text manipulations by other tools such as command-line utils.
=> misc/ports: write-file-string & write-file-lines

doc/reference/requests.md, src/std/net/request.ss
This was largely modelled after Python's requests, which I assume is the intent here.  Python's differs in that the user must construct an authorization subclass, e.g. HTTPBasicAuth(user,pass), and pass that for `auth`; the style here seems more lisp-y and less OOP-y.
This does **NOT** yet support user and password in the URL.  I'll take a look at that soon.
=> net/request: Add auth: parameter supporting basic auth

doc/reference/misc.md, src/std/misc/func-test.ss, src/std/misc/func.ss
Quite a lot of procedures take a predicate, but don't take a limit. This helper allows to get "limit like" functionality without rewriting the original procedure to accept a limit parameter.
=> misc/func: pred-limit

doc/reference/misc.md, src/std/misc/func-test.ss, src/std/misc/func.ss
As accepting `#f` as `limit` allows to easier extend existing procedures, I came to the conclusion that it would better fit the use-case of `pred-limit` to accept not only `fixnum` values as `limit`.
```scheme
(def (myfilter pred list (limit #f))
(filter (pred-limit pred limit) list))
> (myfilter even? [1 2 3 4 5 6] 2)
(2 4)
```
=> :std/misc/func expand pred-limit to accept #f as limit parameter too

doc/reference/text.md, src/std/run-tests.ss, src/std/text/yaml-test.ss, src/std/text/yaml.ss
I decided to make its value a function for processing the string keys.  It
seems decently general, but perhaps it is overly general?  Also, I hope
the documentation is clear enough.  Let me know.
=> Add yaml-key-format parameter

doc/reference/core-builtin.md
Describes how entries in the first argument take precedence, adds examples.
=> Improve docs for hash-merge

src/gerbil/prelude/core.ss, src/gerbil/runtime/gx-gambc0.scm
This adds support for custom writers through the `:wr` method.
Many thanks to @belmarca for his investigative work.
Example:
```
(defstruct A (a b c))
(def a (make-A 1 2 3))
> a
#<A #4>
(defmethod {:wr A}
(lambda (obj we)
(case (write-style we)
((mark)
(when (##wr-mark-begin we obj)
(##wr we (A-a obj))
(##wr-mark-end we obj)))
(else
(when (##wr-stamp we obj)
(##wr-str we "#{A ")
(##wr we (A-a obj))
(##wr-str we "}"))))))
> a
#{A 1}
> (set! (A-a a) a)
> a
#0=#{A #0#}
```
=> Custom writers

doc/reference/misc.md, src/std/misc/func-test.ss, src/std/misc/func.ss
Since some time I'm tinkering about new `pred` procedures and how to combine them to extend e.g. `srfi` procedures.
- `pred-after-sequence` is there to find a "thing" after a "patter"
=> pred-after-sequence

doc/reference/misc.md, src/std/misc/list.ss
Convenience functions which help code to be more literal.
We could live without them, but I think its nice to have them.
``` scheme
(drop-until string? [1 'a "b" #\c])
```
vs
``` scheme
(drop-while (? (not string?)) [1 'a "b" #\c])
```
=> std/misc/list: take-until take-until! drop-until

doc/guide/emacs.md
**Tested with:** NixOS 20.03 (Emacs 26.3), Ubuntu 18.04 (Emacs 25.2.2)
An example `use-package` definition to onboard others quicker.
=> Emacs example config

src/gerbil/compiler/driver.ss, src/gerbil/expander/module.ss
Force use of UTF-8 for Gerbil and Gambit source files, overriding any settings from either the end-user's ambient environment, or Gambit's default runtime options.
=> Force UTF8 in source files

src/std/actor-test.ss, src/std/actor/xdr-test.ss, src/std/generic-test.ss, src/std/net/socket/server-test.ss, src/std/run-tests.ss
Make it so you only have to register a test in one place,
so no test is left behind.
Automatically match test files and test suites by name, patching a few files.
Check that no test file is forgotten. I used this zsh command to locate the
missing files (it's damning that zsh is easier for that than gerbil still):
diff -u =(grep '.-test"' run-tests.ss | cut -d\" -f2 | sort -u) =(print -l **/*-test.ss | cut -d. -f1 | sort -u)
Add missing test/utf32-test.
Add explicitly commented-out tests where a running server is required.
=> Refactor run-tests

doc/reference/misc.md, src/std/misc/list.ss
Alias for `delete-duplicates` because the default name is difficult to remember (and too long). There is an interference between the words `delete` and `remove` (I work in E-Learning).
If your interested in the topic, you can find much more information [here](https://www.supermemo.com/en/archives1990-2015/articles/20rules) (check out _'11. Combat interference'_).
=> std/misc/list: alias delete-duplicates to unique

src/std/misc/concurrent-plan.ss
Marc says that on some architectures it might conceivably return 0 (on those architectures, spawning subprocesses might not be available either).
=> Handle architectures on which ##cpu-count is 0

src/gerbil/gxi, src/gerbil/gxi-build-script
Restore the previous GERBIL_HOME autodetection algorithm,
even though it doesn't work when gxi is a symlink:
- Realpath is part of GNU coreutils, not present on Darwin by default.
- In cases where it is a symlink (as when using Nix), Gerbil can and must
be configured with --prefix at which point this autodetection is replaced
by a hardwired path.
- However, compared to the previous version, since we're using ${foo%/*}
once already, let's not use dirname to do the same thing a second time.
=> Don't use realpath, non-standard on BSD

doc/guide/README.md
It turns out that v4.9.0 doesn't build any more, because of some bug in the thread system (errors with deadlock detected in the build).
This bumps the minimum Gambit version to v4.9.3, since this is what we have been testing with.
=> doc: bump minimum version of Gambit to v4.9.3

src/configure
Passing --prefix=/home/foo/bar/ would result in "//" being generated
in the replacements, causing potential troubles. This adds a little
bit of robustness around that for the configure script, chopping it
off if present, and being smarter than blindly `string-append`ing
parts that are to be joined.
=> Be forgiving when `--prefix` passed with trailing '/'

doc/reference/misc.md, src/std/misc/func-test.ss, src/std/misc/func.ss
`pred-and` allows to check if a `pred` holds on multiple circumstances without constructing a filtered list of to-be-checked items beforehand.
=> std/misc/func: pred-and & pred-or

src/configure
otherwise the configure script will bomb.
=> only patch default_gerbil_home in gxi.c if an install-prefix is configured

doc/reference/core-prelude.md, src/bootstrap/gerbil/expander/core.ssi, src/bootstrap/gerbil/expander/core__0.scm, src/gerbil/compiler/driver.ss, src/gerbil/expander/core.ss, src/gerbil/prelude/core.ss, src/lang/build-deps, src/lang/build.ss, src/lang/gerbil/polydactyl.ss, src/std/build-deps, src/std/make.ss
Adds a new special form, `eval-when-compile` that can be used to do evaluation in the compiler context.
This is implemented using a new parameter in the expander, `current-expander-compiling?`, which is set by the compiler driver and `make`.
This allows us to compile `:gerbil/polydactyl` in the background without having to incur any load time penalty from loading `:std/gambit-sharp`.
=> Implement eval-when-compile

doc/reference/core-builtin.md, doc/reference/core-prelude.md, src/bootstrap/gerbil/core.ssi, src/gerbil/prelude/core.ss, src/gerbil/prelude/core.ssxi.ss, src/gerbil/runtime/gx-gambc0.scm, src/std/actor/rpc/server.ss, src/std/net/wamp.ss
The current core [remove](https://cons.io/reference/core-builtin.html#remove) procedure behaves more like srfi-1 [delete](https://srfi.schemers.org/srfi-1/srfi-1.html#delete) with the exception that it only eliminates **one item** from the list and doesn't take a test argument. Therefor the behavior of the current `remove` changes when srfi-1 is imported. This PR renames the procedure to clean-up this pitfall and introduces thereby a breaking change.
=> core: rename 'remove' to 'remove1'

doc/reference/misc.md, src/std/misc/func-test.ss, src/std/misc/func.ss
Changed procedure signature back to `(preds v [test: equal?])`.
=> misc/func: every-of, any-of, pred-every-of, pred-any-of

doc/reference/amb.md, src/std/amb.ss, src/std/build-deps
`amb-collect` (aka `all-of`) was broken, as reported by @eraserhd 
This rewrites it to sanely collect values until amb is exhausted:
```
(begin-amb (let (x (amb 1 2 3)) (required (> x 1)) (all-of x)))
```
Note that `begin-amb` should always be used to start a fresh amb scope in order to avoid leaking side effects.
=> Fix amb-collect

doc/guide/emacs.md, etc/gerbil-mode.el, src/install
This PR fixes #510, there were two problems:
1. `gerbil.el` did not set the `major-mode` to `gerbil-mode`
2. `gerbil.el` provided `gerbil` but spacemacs and `use-package` expected it to provide `gerbil-mode`
1. rename `gerbil.el` to `gerbil-mode.el`
2. add `(setq major-mode 'gerbil-mode)`
3. change `(provide 'gerbil)` to `(provide 'gerbil-mode)`
This should not be an invasive change in any way, but I have not tested it in vanilla emacs so please try it and reject if it changes the workflow. If it impacts the vanilla emacs workflow in any way then I'll just pull a mirror copy for the `spacemacs` layer and maintain it. Any comments on ways to better contribute also appreciated.
Thanks!
=> Correcting major-mode for gerbil.el, see #510

doc/reference/amb.md, src/std/amb.ss
Adds a new `begin-amb-random` construct for explicitly requesting randomized search strategy, which is now by default deterministic.
Previously it was always randomized.
cc @eraserhd
=> Make amb search strategy parametric, default to deterministic

doc/reference/amb.md, src/std/amb.ss
This would sometimes fail, because the required clause is be outside the collect scope:
```
(begin-amb-random (let (x (amb 0 1 2)) (required (not (= 0 x))) (all-of x)))
```
This fixes the issue by introducing a parameter that prescribes the behaviour of `amb-fail`; when set, it is a thunk that continues at the end of the collection; otherwise it just raises.
Note that we have completely deviated from the original chicken egg that served as inspiration at this point; there, `all-off` is a scope construct (not really, but almost because it uses mutation of global variables and it's also completely undocumented) that collects from ambs within the expression context.
In the Gerbil implementation, `all-of` just appears within an amb scope to perform a collect+cut.
cc @eraserhd
=> make amb-collect reliable

doc/reference/text.md, src/std/text/csv.ss
A convenient procedure to improve working from the REPL with csv.
=> std/text/csv: add write-csv-file

src/std/build-deps, src/std/text/json.ss
Instead of cons+reverse!, just accumulate the list inline by setting the tail.
Follow up from #535.
=> json: optimize list parsing with inline list accumulators

doc/reference/amb.md, src/std/amb-test.ss, src/std/amb.ss
CHICKEN calls this `amb1` or `choose`.  The first name is not readable IMHO, and the second is sort of, but seems more like something related to binomial distributions.  Also the sense of the word seems wrong (amb[iguous] is an adjective, and choose is imperative).
I considered `<-` as an alias, which is what Haskell uses for set builder, but that's actually a hack to look like ∈ and also used in gerbil's actors, so no.
=> Add element-of to :std/amb

doc/reference/misc.md, src/std/misc/string-test.ss, src/std/misc/string.ss
Handy Clojure like procedure that converts a single thing into a string or appends multiple string into one.
``` scheme
> (str 1.0)
"1.0"
> (str "foo" "bar")
"foobar"
```
I tried to get the output as human friendly as possible by e.g. converting numbers from `2.` to `2.0`.
=> std/misc/string: str

src/install
The homebrew install removes them after, and this should be removed
from it for the next release.
=> Do not install .keep files

src/std/build-deps, src/std/misc/concurrent-plan.ss
Wrap uncaught exceptions from `thread-join!` into a `worker-error` that has a useful display exception method.
Also cleans up unnecessary imports in the file.
=> Fix concurrent plan error reporting

src/gerbil/expander/module.ss, src/gerbil/expander/root.ss
A much requested feature.
When not in module context (or an internal expansion), it is ignored.
This allows us to have scripts that are also modules and use export.
=> allow exports in top context

src/std/net/request.ss
When writing post data, adding an extra newline may cause some
web servers to close the connection before sending a response
because the extra newline isn’t accounted for in the post/put data’s
content length. Removing the newline seems to fix the problem. This was
encountered posting a capabilities document to `chromedriver`’s
/session endpoint. An alternate fix is to include the new line in the
content-length calculation.
=> Remove newline when writing http post/put data

doc/guide/getting-started.md, doc/reference/make.md, src/std/make.ss
Disable the parallel build unless explicitly enabled, as it confuses some
newbies to no end as the compilation semi-deterministically dies out of
lack of memory as gerbil tries to spawn too many gcc's. In the future,
somehow find a good estimate of how many processes to spawn, or better,
learn to dynamically measure and calibrate.
=> Disable parallel build by default

src/std/db/_mysql.scm
This fix is in reference to #571 
I'm not well versed in C, but decided to take a try at resolving this.
=> issue-571: attemped to replace my_bool with c99 bool for mysql bindings

src/gerbil/prelude/gambit/ports.ss
I haven't been able to find anywhere in r7rs that requires `k` to be positive instead of non-negative for `read-bytevector` or `read-string`.  I checked chibi's `read-string`, and `(read-string 0) ;=> ""`, so as far as I can tell,
this is right.
=> Allow for reading zero length u8vectors and strings

src/std/srfi/115.ss, src/std/srfi/srfi-115/regexp.scm
posse hash-table: state -> searcher
(equal?-hash state) is more discriminant than (eq?-hash state)
fixes #598
=> srfi-115: fix posse hash-table collisions

src/std/srfi/124.ss
The implementation behaves a bit weirdly — if you inspect the `ephemeron-key` in the REPL, the ephemeron won’t be broken until the datum *also* has no references anywhere else. I assume this is something to do with Gambit’s GC/REPL/object table/whatever, and I’m not about to start poking around in there. But in essence, it works:
```scheme
> (define a (list 1 2 3))
> (define b (cons 4 5))
> (define e (make-ephemeron a b))
> (set! a #f)
> (##gc)
> (ephemeron-broken? e)
#t
> (ephemeron-key e)
#f
> (ephemeron-datum e)
#f
```
I’m also not quite certain this is a correct implementation of `reference-barrier`. Afaict even in a full implementation it’s just a void procedure meant to keep a certain value on the stack and therefore accessible?
(Also, like in Chibi, the ephemeron will never be …
=> Add a real implementation of SRFI 124 based on Gambit's wills

src/std/db/postgresql-driver.ss, src/std/db/postgresql-test.ss, src/std/db/postgresql.ss
Here is my most recent version. I tried to do a proper subtree with history but it didn't work out so here are the changes in "order": [gerbil-postgresql](https://github.com/drewc/gerbil-postgresql)
Also this master has some small changes to ./configure that are in this pull request because I couldn't figure out how to remove them. Sigh. :)
=> PostgreSQL Simple Query, revise -statement with -command

configure, doc/reference/sugar.md, src/std/misc/repr.ss, src/std/sugar-test.ss, src/std/sugar.ss
Improve `assert!` error message, add `extra-expr`s.
```scheme
(assert! condition-expr [message-expr extra-expr ...])
```
Raises an error when the `condition-expr` evaluates to false.
If the `message-expr` and `extra-expr`s are provided, their
values will be included in the error message.
```scheme
> (import :std/sugar)
> (def e 'needle)           
> (def l ['stack 'of 'hay])
> (assert! (member e l))
*** ERROR -- Assertion failed (stdin)@4.10: (member e l)
e => 'needle
l => ['stack 'of 'hay]
```
=> Improve assert! error message, add extra-exprs

doc/.vuepress/config.js, doc/reference/assert.md, doc/reference/sugar.md, src/std/assert-test.ss, src/std/assert.ss, src/std/build-deps, src/std/build-spec.ss, src/std/make.ss, src/std/misc/concurrent-plan.ss, src/std/misc/list.ss, src/std/run-tests.ss, src/std/sugar-test.ss, src/std/sugar.ss, src/std/text/csv.ss, src/std/text/hex-test.ss
so that `:std/sugar` doesn't have any runtime dependencies.
=> move assert to its own module

src/std/assert-test.ss, src/std/assert.ss
The `assert!` implementation just merged in #643 didn't work on calls to keyword functions. This PR fixes it so that it never tries to treat keywords as extra-exprs.
=> Fix assert! on keyword functions

src/std/text/base58-test.ss, src/std/text/base58.ss
Calling `make-u8vector` without the fill argument leaves the contents of the u8vector unspecified, so this PR fills the leading zeros u8vector with `0`.
This PR also changes `(alphabet-decode ab int)` to `(alphabet-decode ab char)`, and adds tests for `base58-decode` and `base58-encode`.
=> Fix base58-decode leading zeros

src/std/crypto/libcrypto-rfc5114.c, src/std/crypto/libcrypto.ss
LibreSSL 3.5 has made HMAC_CTX and DH opaque so code using it should be switched to use accessor functions.
Lifted from OpenBSD port patches.
=> fix for LibreSSL 3.5

src/build.sh
Use generic C compiler name instead of using hard-coded gcc. OpenBSD uses clang as default c compiler on most archs so this allows it to build gerbil.
The ports in OpenBSD provide gcc as well but in that case the binary is named egcc so it will not match the name either.
Use the standard CC variable to look up c compiler to use and default to cc.
=> fix: do not hard-code gcc

src/gerbil/prelude/core.ss, src/gerbil/runtime/gx-gambc0.scm
This is a utility function, in the runtime, to easily chain keyword argument handlers.
It converts a keyword table to a rest argument list, removing the specified (presumably already processed) keywords.
Example:
```
(def (foo a: a b: b c: c)
....)
(def (bar #!key kws d: d)
(apply foo (kreyword-rest kws d:)))
```
=> add keyword-rest utility function

src/std/make.ss
The compilation errors lack context, as the exception is mangled into just the message.
This fixes the issue and properly propagates the error from the worker and displays the exception with context.
=> properly display errors from build jobs

src/gerbil/prelude/core.ssxi.ss
Reverts vyzo/gerbil#682
It turns out that the random procs don't accept a source, but instead you have to make them from the source with the `random-source-make-*` procedures; facepalm.
=> Revert "fix arity declarations for random procedures"

doc/guide/ffi.md, doc/reference/foreign.md, src/std/foreign-test.ss, src/std/foreign.ss
Additions to resolve issues as explained in #614.
The new form of the `define-c-struct` macro adds two optional positional arguments:
```scheme
;; . . .
;; compatible-tags => list of symbols representing additional C type declarations compatible with struct
;;    This is usually the name of a typedef alias, when it differs from the C struct tag.
;; as-typedef => set to #t when defining an anonymous typdef'd struct
;;    In this case, `struct` should be the name of the typedef alias.
(define-macro (define-c-struct struct #!optional (members '()) release-function compatible-tags as-typedef)
```
The procedure's interface could be made nicer with named optionals if backward compatibility is not a priority, otherwise specifying `#f` for `release-function` and `compatible-tags` will occur often …
=> Expanded utility of `define-c-struct`

doc/guide/README.md
Gerbil getting started docs say to pull a docker image with tag `gerbil/scheme` but there is no such image on Docker Hub at present. There is an image `docker/ubuntu` which works as expected. This PR fixes the doc to match the existing image tag.
=> Fix docker instructions to match the current published image name

src/std/crypto/etc.ss, src/std/crypto/libcrypto.ss, src/std/db/_sqlite.scm, src/std/db/_sqlite.ssi, src/std/db/sqlite.ss, src/std/getopt.ss
- Use sqlite3_prepare_v3 instead of _v2
- Use libcrypto instead of urandom for random-bytes, which is cheaper and more portable
=> Tweaks to the std library

doc/reference/requests.md, src/std/net/request.ss
I wanted to make a PATCH request and realised I couldn't.
A potential improvement is to expose the list of acceptable methods from the module.
=> requests: add http-any

src/gerbil/prelude/core.ssxi.ss, src/gerbil/prelude/gambit/os.ss, src/std/misc/symbol.ss
Closes #707 
a potpuri:
- tty-mode-reset does not have a public primitive; there is only `#tty-mode-reset`
- fix arities for tty functions, they were mostly broken
- fix `std/misc/symbol` exports while at it.
=> misc: tty arities and symbolic exports

doc/reference/os.md, src/std/build-deps, src/std/build-spec.ss, src/std/os/temporaries.ss
Adds `:std/os/temporaries` with a reasonably sane frontend to mktemp.
=> Some utilities for working with temporary files

doc/reference/test.md, src/tools/gxtest.ss
- add support for module scoped setup and cleanup functions.
If exported, `test-setup!` will be executed before any test suites exported by the module and `test-cleanup!` will be executed on unwind from module test suite exection.
- add a -r/--run option to gxtest to only run test suites that match a regex.
=> gxtest refinements

doc/reference/test.md, src/tools/build-deps, src/tools/gxtest.ss
- update forgotten build-deps
- don't run setup/cleanup for a module when all test suites are filtered
- fix typos
=> gxtest: misc polish touches

.github/workflows/ci.yml, src/std/crypto/libcrypto.ss, src/std/crypto/pkey-test.ss, src/std/crypto/pkey.ss
Closes #711 
Issues resolved by this pr:
- broken gambit builds (thanks @ober!)
- broken digest-sign and digest-verify in libcrypto
=> Fix Sad CI

src/std/getopt.ss, src/tools/gxpkg.ss, src/tools/gxtags.ss, src/tools/gxtest.ss
We don't have anything describing the program itself; this fixes.
=> getopt: add a global help option for describing the program

src/gerbil/prelude/gambit/fixnum.ss, src/std/interface.ss, src/std/test.ss
Cherry picked from #728.
Summary:
- fix issues with the syntax quoting in mixin interface methods; syntax-local-introduce is appropiate
- don't generate dynamic method bindings for interfaces, it defeats the purpose.
- fix a typo in `:gerbil/gambit/fixnum`
- improve check failure reporting in `:std/test` to also display the expected value.
=> Miscellaneous fixes

doc/reference/interface.md, doc/reference/sort.md, src/std/interface.ss, src/std/misc/symbol.ss
With-lock is nice (and exception safe) but unfortunately it allocates a closure and does dynamic-wind; not the best of ideas if you care about perf.
=> Avoid with lock in some perf sensitive operations

doc/reference/misc.md, src/std/build-deps, src/std/build-spec.ss, src/std/misc/rwlock-test.ss, src/std/misc/rwlock.ss
Sorely missing them! Cherry picked from #728
=> Read-Write Locks

src/std/crypto/libcrypto.ss
add LibreSSL feature flags and use them to selectively enable parts which are implemented by it. Fixes issue #745.
=> fix: add LibreSSL compatibility to libcrypto

src/std/test.ss
so that you don't have to guess where the exception is coming from!
=> gxtest: print stack traces on exceptions

Makefile.in, configure, configure.ac
The thing was flat out broken; instead of installing under prefix it installed under `prefix/gerbi/something` and linked the binaries. This is the wrong thing to do: when the user says prefix he means prefix, not some random directory underneath.
=> Fix configure and Makefile

src/gerbil/compiler/driver.ss
- fix the order or decls in static exe compilation; gx-gambc0 ended ignoring prelude declarations
- add a timestamp to modules with runtime code; this is useful for testing for the presence of code in static binaries.
=> compiler/driver: a couple of small fixes

src/gerbil/compiler/driver.ss
It has been observed that parallel build with make was suffering with the occasional gremlin error; this was due to lack of concurrency protection in the compiler driver.
This modifies the driver to use a mutex to protect critical sections that modify "global" data structures and should be serialized.
=> compiler driver: add mutex protecting critical sections

doc/reference/getopt.md, src/std/build-deps, src/std/getopt.ss, src/tools/gxpkg.ss, src/tools/gxtags.ss, src/tools/gxtest.ss
Adds a call-with-getopt entry point to eliminate boilerplate.
=> Some getopt improvements: call-with-getopt

doc/guide/README.md
just a quickie, fixes the erroneous default prefix referred to in the installation instructions.
=> fix installation guide default prefix bug

doc/reference/stdlib.md
obsolete documentation in `stdlib.md`.
=> yet another quick doc fix

configure
Fix the following error when running ./configure:
sed: -e expression #1, char 21: unterminated `s' command
=> Fix sed invocations in configure script

docker/Dockerfile
=> Use new build format

doc/guide/getting-started.md, src/build/build-libgerbil.ss, src/gerbil/compiler/driver.ss
Seems to be causing problems with various ars, so we get rid of it and do the same thing we do with libgerbil.so.
=> fix ar situation: don't put the ldd inside libgerbil.a

doc/guide/README.md, doc/guide/bootstrap.md, doc/guide/emacs.md, doc/guide/intro.md, doc/guide/shell.md, doc/tutorials/httpd.md, doc/tutorials/kvstore.md, doc/tutorials/languages.md, doc/tutorials/proxy.md
We are in the future, no need to confuse people (and the system!) with things of the past.
=> doc: remove references to GERBIL_HOME

configure, docker/Dockerfile, src/build/build-libgerbil.ss
Until gerbil TLS/SSL is ready, we want to --enable-openssl in gambit so that we don't break existing net/request users.
This fixes the situation and also fixes the handling of `LDFLAGS` as there were bugz.
=> Enable openssl for now, and appropriate usage of LDFLAGS

doc/reference/stdio.md, src/std/io/interface.ss
Introduces a `Closer` base interface to stdio so that we don't repeat ourselves.
=> IO Closer interface

doc/reference/db.md, src/std/db/mysql.ss
Honestly, it's 10 years later and there is still no protocol spec to develop a native driver.
This was meant to be a temporary driver until we could get a gerbil native driver, and this is not happening.
So deprecate and remove after v19.
**Note** If you are using MySQL and want to keep the driver alive, please step up to host it and maintain it out of tree. This will also let us remove it earlier.
=> Deprecate mysql driver

configure
llvm just can't deal with it in that BSD.
=> configure: drop native march for OpenBSD

configure, src/std/actor-v13/rpc-test.ss, src/std/actor-v13/xdr-test.ss, src/std/build-features.ss, src/std/build-spec.ss, src/std/net/socket/server-test.ss
The build time is getting long, and this also adds code mass for legacy code; so don't do it by default.
=> don't build deprecated stdlib packages by default

doc/reference/actor.md, doc/tutorials/ensemble.md, src/std/actor-v18/admin-test.ss, src/std/actor-v18/admin.ss, src/std/actor-v18/api.ss, src/std/actor-v18/ensemble.ss, src/std/actor-v18/loader-test-server.ss, src/std/actor-v18/loader-test.ss, src/std/actor-v18/loader.ss, src/std/actor-v18/message.ss, src/std/actor-v18/proto.ss, src/std/actor-v18/registry.ss, src/std/actor-v18/server-test.ss, src/std/actor-v18/server.ss, src/std/build-spec.ss, src/std/crypto/kdf.ss, src/std/crypto/libcrypto.ss, src/std/crypto/pkey.ss, src/std/net/httpd-test.ss, src/std/net/httpd/server.ss, src/tools/gxensemble.ss
This adds support for (optionally) restricting administrative actions from remote actors to servers authorized using an Ed25519 key pair.
This came up in discussions with @belmarca and I think it is quite a useful addition.
Edit: After discussion with @fare, I added fine-grained capabilities besides admin (admin implies everything else) and the ability for a server to delegate capabilities, provided it can prove it has the administrative private key.
=> Actors v18: Administrative privilege separation and capabilities

src/build.sh
We don't use them gsis, so why confuse people by putting it in GERBIL_PREFIX/bin?
=> move gsi out of the way

src/std/build-spec.ss, src/std/misc/template.ss
This adds some basic template facilities for named substitution of variables.
It currently supports `${var}` substitution, where the value is passed with a keyword argument `var:` for the name of the var.
Cherry picked from #816.
=> Basic Templates

src/std/db/dbi.ss, src/std/db/mysql.ss, src/std/db/postgresql.ss, src/std/db/sqlite.ss
So that we don't have to do dynamic dispatch; also ensures there are no latent errors from dynamic dispatch.
Closes #748
=> Use interfaces in SQL DBi

src/build.sh, src/gerbil/main.ss, src/std/build-script.ss, src/std/make.ss, src/tools/gxpkg.ss
This is the make side:
- By defining build-release (setenv `GERBIL_BUILD_RELEASE=t`), exe: means static-exe:
- By defining build-optimized (setenv `GERBIL_BUILD_OPTIMIZED=t`), exe means optimized-exe:
- By defining both, exe means optimized-static-exe:
This is the `gxpkg build` side:
- pass `--release` flag to build with build-release defined
- pass `--optimized` flag to build with build-optimized defined
- invoke `gxpkg build` to do it in the current directory; no package linking needed any more.
And this is the `gerbil` bach synonym:
- `gerbil build [--release] [--optimized]` means `gxpkg build ...`
It also adds a `clean` command to builds scripts, and moves the clean logic out of gxpkg and into make, where we have the spec outputs anyway.
See #780
=> introduce context dependent variation of exe: build spec

configure, src/gerbil/main.ss, src/tools/gxpkg.ss
Implements  `gerbil new` as a synonym for `gxpkg new`; this creates a new package template in the current directory.
=> gxpkg new command

src/std/build-script.ss, src/tools/gxpkg.ss
Typo in the hash get; also made them options for the build script.
=> fix build --release and --optimized

src/std/net/ssl/api.ss, src/std/net/ssl/libssl.ss
let's not have to worry about downgrade attacks.
=> set TLSv1.2 as minimum version for SSL/TLS contexts

doc/guide/README.md, doc/guide/getting-started.md
Thanks to @leahneukirchen we can now just `make -j4` instead of having to set the build cores during the build.
This documents it.
=> document make -j

.github/workflows/ci.yml, docker/Dockerfile
See https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources
=> CI: use all vm cores in github workers

Makefile, doc/guide/README.md, docker/Dockerfile, src/build.sh
The magic incantation in the Makefile doesn't work. This uses a hack to fix it, but also doesn't break the default user GERBIL_BUILD_CORES if no -j is passed, so a win overall.
=> fix make -j passing build cores

src/gerbil/runtime/error.ss, src/gerbil/runtime/gambit.ss, src/std/error.ss, src/std/xml/_libxml.scm, src/std/xml/sxml-to-xml.scm
A couple of utility macros in `:std/error` to aid error raisers.
Also fixes clown shoes with double `*** ERROR` display in the repl.
=> Macros for exception context

doc/guide/env-vars.md, doc/guide/getting-started.md, doc/guide/package-manager.md, doc/reference/dev/bach.md, doc/reference/dev/build.md, doc/reference/dev/optimizing.md, src/gerbil/main.ss, src/tools/gxpkg.ss
On top of #918 
Adds documentation for the drastic changes in gxpkg.
=> Document the new world order for builds

doc/guide/env-vars.md, doc/guide/getting-started.md, doc/guide/package-manager.md, doc/reference/dev/bach.md, doc/reference/dev/build.md, doc/reference/dev/optimizing.md, src/gerbil/main.ss, src/tools/gxpkg.ss
This addresses the global-vs-local state madness with .gerbil:
When we are in local package context, we create a new local .gerbil to use for the build, which gives us isolation.
We also create manifests for all the individual packages, so that we can get meaningful error reports.
On top of #916.
See also #651
=> Build Isolation and Manifests

src/std/text/basic-parsers-test.ss, src/std/text/basic-parsers.ss
Fix early-onset bitrot, add a couple regression tests.
=> Fixes to basic-parsers

src/gerbil/gxi-main.ss, src/std/actor-v13/rpc/connection.ss, src/tools/gxpkg.ss
Also fix a typo in multiple places
=> Add -L --load to gxi

src/std/net/httpd/handler.ss
def-http-condition was _broken_; the working build was failing haphazardly with 
```
*** ERROR IN #:loop97259, "misc/concurrent-plan.ss"@88.7 -- Build Failure at net/httpd/server
*** ERROR IN ?
--- Syntax Error: Bad syntax; not a syntax binding
... form:   message
```
It was infrequent enough that I treated as an annoyance, but I had it happen quite a few times today, so I fixed it.
Also fixes the `http-response-write-condition` api which was also _terminally broken_.
It would simply crash without passing any parameters.
@fare please be careful with such things in the future, the handler is using `(not safe)` at module level.
=> Fix broken http condition def and http-response-write-condition api

src/std/net/socks/client.ss
Avoid the intermediate buffer which copies the u8vector; this way we just write it directly to the socket on flush.
=> A tiny improvement in socks client

src/std/xml-test.ss, src/std/xml/sxml-to-xml.scm
=> `link` element no longer has closing html tag

src/gerbil/prelude/core.ss, src/gerbil/runtime/thread.ss, src/std/actor-v18/api.ss, src/std/actor-v18/connection.ss, src/std/actor-v18/loader.ss, src/std/actor-v18/message-test.ss, src/std/actor-v18/registry.ss, src/std/actor-v18/server.ss, src/std/actor-v18/test-util.ss, src/std/db/postgresql-driver.ss, src/std/error.ss, src/std/misc/threads.ss, src/std/misc/wg.ss, src/std/net/httpd/server.ss, src/std/net/socks/server.ss, src/std/net/ssl-test.ss
=> automatically wrap actor threads with exception stack trace dump

src/gerbil/compiler/driver.ss, src/gerbil/gxc-main.ss, src/gerbil/main.ss, src/gerbil/prelude/core.ss, src/gerbil/runtime/init.ss, src/gerbil/runtime/system.ss, src/std/actor-v18/loader-test-server.ss, src/std/actor-v18/path.ss, src/std/make.ss, src/tools/gxensemble.ss, src/tools/gxpkg.ss
Defines `(gerbil-path)` in the runtime so that we don't have to `getenv` it right and left.
=> Define gerbil-path

src/std/os/signal-00-signalfd-test.ss, src/std/os/signal-01-signal-handler-test.ss
They tend to fail once every few runs, which may block prs of unrelated functionality.
=> Disable flaky signal tests

configure, homebrew/README.org, homebrew/gerbil-scheme.rb, install.sh
MacOS did not have a find argument that was used in installl.sh. Added `gfind` to the recipe and modified the install. 
Also removed the extra v as I got sick of `/opt/homebrew/Cellar/gerbil-scheme/0.18/vv0.18-rc1/lib/std/xml__rt.o1`
If we plan to tag without a v we can put it back.
=> Install fixes for MacOS (and remove the extra v)

src/std/misc/uuid.ss
Fixes https://github.com/mighty-gerbils/gerbil/issues/989
`random-uuid` now sets the variant and version fields.
- https://www.rfc-editor.org/rfc/rfc4122#section-4.1
=> Make random-uuid generate UUIDv4

src/gerbil/prelude/gambit.ss
=> add some missing homegeneous vector symbols

.gitignore, src/gerbil/runtime/init.ss, src/gerbil/runtime/version.ss, src/std/make.ss
0. Kill version.ss, the v0.19 development cycle has started.
1. make clean should not try to delete things that don't exist and fail
2. normalize load-path order: 1. GERBIL_LOADPATH 2. GERBIL_PATH/lib 3. GERBIL_HOME/lib (2 is excluded during the build)
=> A couple of fixes

Makefile
When the `build` directory exists, the build target needs to be in .PHONY, such that make would consider remaking `build`.
=> Makefile: add build to .PHONY

src/std/net/ssl/libssl.ss
Fixes compilation under:
gcc --version
gcc (Ubuntu 10.5.0-1ubuntu1~20.04) 10.5.0
uname -ovm
#98~20.04.1-Ubuntu SMP Mon Oct 9 16:43:45 UTC 2023 x86_64 GNU/Linux
=> fix build on gcc 10

doc/.vuepress/config.js, doc/reference/std/db/dbi.md, doc/reference/std/db/postgresql.md, src/std/db/postgresql-driver.ss, src/std/db/postgresql-test.ss, src/std/db/postgresql.ss, src/std/io/bio/api.ss, src/std/io/bio/delimited.ss, src/std/io/bio/input.ss, src/std/io/bio/output.ss, src/std/io/bio/util.ss, src/std/io/delimited.ss, src/std/io/interface.ss, src/std/io/port.ss, src/std/io/socket/socket.ss, src/std/io/strio/api.ss, src/std/io/strio/delimited.ss, src/std/io/strio/input.ss, src/std/io/strio/output.ss, src/std/io/strio/util.ss, src/std/net/socket/api.ss, src/std/os/error.ss, src/std/os/signal-handler.ss
Add support for SSL in PostgreSQL client
=> PostgreSQL SSL support

doc/reference/std/net/json-rpc.md, src/std/net/json-rpc.ss
`:std/net/json-rpc/transport-error` looks to have the wrong name, so this PR fixes that.
=> Fix `:std/net/json-rpc/transport-error`

src/std/os/error.ss
=> Export error codes

src/gerbil/compiler/driver.ss
=> Avoid conflict in intermediate files for executables

doc/reference/gerbil/prelude/macros.md, doc/reference/std/misc/vector.md, doc/reference/std/sugar.md, src/gerbil/prelude/core.ss, src/gerbil/prelude/gambit.ss, src/std/misc/vector.ss, src/std/sugar-test.ss
I moved the existing documentation, perhaps there's a better place tho.
=> define vector-ref-set! and u8vector-ref-set! in core prelude

src/std/srfi/128.ss
`default-comparator` is not defined.
=> std/srfi/128: comparator-if<=> should use make-default-comparator

doc/reference/std/misc/evector.md, src/std/misc/evector.ss
Add an optional init: argument to memoize-recursive-sequence to cover the usual case when users don't care to use list->evector.
=> Improve evector

doc/guide/getting-started.md, doc/reference/gerbil/prelude/core-expander-syntax.md, doc/reference/std/generic.md, doc/reference/std/iterators.md, doc/reference/std/make.md, doc/reference/std/stxparam.md
- Reference - Prelude - Core Expander Syntax: the opening paragraph now links to the reference of the `current-expander-context` instead of 404ing.
- fixed comment spacing in the `core-expand` example.
- Reference - Standard Library - Generics: all the predefined types starting with `<` failed to render on the site, this has been corrected and they should now render correctly, including the sidebar content of said types.
- Reference - Standard Library - Iterators: now correctly links to the Guide explaining iterators.
- refer to "the guide" on in on the website itself as "Guide" with uppercase G. This seemed to be a pattern in other parts of the docs.
- Reference - Standard Library - Syntax Parameters: link to the `std/actor-v18/message.ss` instead of `actor`. `actor` does not exist, only …
=> Docs: 404 links, `generic.md` headlines, misc

doc/guide/macos.md, homebrew/README.org, homebrew/gerbil-scheme.rb
18.2 should work for everyone, right? :)
=> Working 18.1 homebrew. I blame git for thinking it worked.

README.md
I made the following minor changes to the README.md file.
* Changed "h" to "H" in the word, "GitHub"
* Modified the simile toward the top of the file
* Changed "Systems Programming" to "systems programming" (lowercase "s" and lowercase "p")
=> Minor grammar updates to the README file

doc/.vuepress/config.js, doc/build.sh, doc/reference/std/mime/README.md, src/std/build-spec.ss, src/std/mime/README.org, src/std/mime/mime.types, src/std/mime/struct.ss, src/std/mime/types.ss
I also snuck in a build fix for libssl on mac
=> New :std/mime/types

src/std/protobuf/macros.ss, src/std/protobuf/protobuf-test.ss
unchecked call to write-varint* ... with arguments in the wrong order. :facepalm:
=> fix bug in protobuf expansion

doc/reference/std/sugar.md, src/std/sugar-test.ss, src/std/sugar.ss
Some tables contain string keys. Having let-hash properly handle string keys is thus important. The '.$id' syntax is short and in line with the other prefixes in let-hash. Weak accessor only.
=> Add syntax for string keys in let-hash.

src/gerbil/compiler/driver.ss
so that we can actually debug such things (e.g. bad declarations).
Note: I am not recompiling the bootstrap here, as there is no need and I don't want to create unnecessary conflicts with the metaclasses pr.
=> error diagnostics for invocation failures

src/std/interface.ss, src/tools/build.ss, src/tools/env.ss, src/tools/gxensemble.ss, src/tools/gxprof.ss, src/tools/gxtags.ss, src/tools/gxtest.ss
So that we dont have to `gerbil env gerbil test` and :facepalm: 
Also, #1131 didn't quite fix the bug :scream_cat:
=> consistently take local package context into account in gerbil tools

src/std/io/bio/bio-test.ss, src/std/io/bio/util.ss, src/std/net/httpd/logger.ss
So that we don't have to `number->string` right and left; and of course the httpd logger uses it.
=> Bio methods to read/write integers in decimal

src/std/srfi/1.ss, src/std/srfi/43.ss, src/std/srfi/srfi-1.scm, src/std/srfi/srfi-43.scm
Updates and minor fixes for gambit integration.
- remove obsolete defs of procedures now provided as gambit builtins.
- fix srfi 43 exports
=> minor fixes (not quite bugs) for gambit integration

src/gerbil/runtime.ss
=> explicitly set the gerbil runtime namespace

src/std/interactive.ss
This now expands to an empty statement and breaks the module.
=> Remove obsolete import statement.

src/std/build-spec.ss, src/std/db/_sqlite.ssi, src/std/os/_socket.ssi, src/std/ssi.ss, src/std/text/_zlib.ssi, src/std/text/base64.ssi
This to avoid externing the symbols, they really should be define-runtime'd but it was cumbersome before.
Hence the all new .ssi prelude, which also helps restrict what you can do in an .ssi as a step towards normalizing the format.
=> prelude for hand-written .ssi files

src/std/net/httpd/handler.ss
replace #u8vector by <u8vector> in irritants upon os-error in http handler
=> os-error: replace #u8() by '<u8vector>' in irritants

src/std/make.ss
it was observed that exes compiled inline and not as compile jobs.
=> minor fix: mark exe compilation as parallel

doc/reference/std/net/json-rpc.md, src/std/net/json-rpc.ss, src/std/net/websocket/client.ss, src/std/net/websocket/server.ss
Some JSON-RPC servers do not accept `Content-Type: application/json-rpc`. The programmer must now specialize their code for their own uses.
The WebSocket client was wrongly terminating when the server did not respond with a Sec-Websocket-Version header. Our logic was flawed and we now fail when it is present. See https://datatracker.ietf.org/doc/html/rfc6455#section-4.4.
=> Fixes to JSON-RPC and WebSocket clients

src/std/iter-test.ss, src/std/iter.ss
the various iteration macros (e.g. for) accept any object with the :iter generic defined; however when a filter clause was present iter wasnt called
fixes #1211
=> call iter on the iterable when filtering

doc/guide/emacs.md
Added a bit of help for actually installing the packages for doom emacs. I had a hard time figuring out how to actually get the packages working so I added a little bit of clarification that you must run `doom sync` from the command line outside of doom emacs.
=> Doom emacs package instructions

doc/.vuepress/config.js
Currently sidebar and header links are sometimes empty because of VuePress's slugify rules.  When the URL fragment is empty, the page has a tendency to jump around while viewing it.  For example "->" on
https://cons.io/reference/std/actor.html exhibits this behavior.  This makes viewing the docs occasionally painful, as the page may scroll to the top while viewing it.
While fixing the issue, we might as well have nicer links also, so some work has been done to make common characters and patterns have more descriptive link names.  For example:
* "->" becomes "to"
* "!" becomes "bang"
* "--..." becomes "dashes"
=> Prevent invalid URL fragments

src/build/build-bach.ss, src/build/build-libgerbil.ss
Compilation was breaking due to undefined 'openpty' for both build-libgerbil.ss and build-bach.ss.
Back required -lm as well.
=> Fix freebsd builds for missing openpty

src/gerbil/core/sugar.ss
Enforce the at least one expression in the body constraint, so that error reporting is understandable.
=> improve when/unless error reporting

src/gerbil/core/contract.ss, src/gerbil/test/compiler-test-support/interface-mixin.ss, src/gerbil/test/compiler-test.ss
they were broken in the transition to core.
=> fix interface mixins

src/std/net/json-rpc.ss
A 2-char patch.. `json-rpc`s `internal-error` can take an optional (default void) `e` for the error/exception object. Its one call in `json-rpc` does have an `e` in scope that wasn't passed but probably should be. Hence this patch!
=> In `serve-json-rpc`, populate `internal-error` with exception

src/std/cli/multicall.ss
display-build-manifest now always want a port, and to get the string one must use build-manifest-string. So use display-build-manifest then newline.
=> Fix help after change in display-build-manifest

doc/guide/eval.md
Expand the guide for `eval` with a use case (configuration file) and a trick (quasiquotation).
=> Expanding the guide for eval

doc/reference/std/misc/number.md
rename heading `least-integer?` to `least-integer`
=> fix typo in :std/misc/number documentation

docker/Dockerfile, docker/Makefile
To reflect accurately which version of gerbil is installed. This differs from just using "master".
=> Fix docker packages names

src/tools/gxhttpd.ss
That was against the standard.
=> Fix gxhttpd bug: No content length when chunking

src/std/net/repl-test.ss, src/std/net/repl.ss
=> Fix arity error in :std/net/repl

src/std/net/s3/api.ss, src/std/net/s3/sigv4-test.ss
I experienced some critical errors when trying to use the S3  library with Google Cloud Storage. The library now handles AWS' and Google's S3 API correctly.
I also fixed (what I assume to be) an error reporting mistake in the `with-request-error` procedure
I tried writing tests for `s3-parse-xml`, but I had a pretty rough time trying to artificially create a `request` instance that correctly responds to `(request-content req)` with a  pre-supplied string. Implementing a one-off struct that implements `StreamSocket` seemed excessive. I ultimately gave up, considering how little "novel" functionality exists in `s3-parse-xml`, but I guess we could split the procedure and test "just the XML" part.
Let me know if any additional tests are necessary.
=> Make standard S3 library also compatible with Google Cloud Storage

configure
Importantly, fixes fixnum operations.
=> Update Gambit to latest v4.9.6-14-gb46d47a8

doc/reference/std/net/s3.md, src/std/net/s3/api.ss, src/std/net/s3/interface.ss
This functionality might seem redundant, but there are some pretty severe drawbacks to using existing options:
- Using `S3Bucket-get` works _alright_ as a proxy, especially if the file doesn't exist (mapping the thrown error to `#f`). However, if the file **does** exist, downloading the file to confirm its existence is a waste, especially if the file is large
- Using `S3Bucket-list-objects` can work well, but only if the quantity of objects is small and/or the list of objects rarely change (enabling caching)
I tried to make the method name match existing conventions, but it might create an unfortunate ambiguity: `S3Bucket-exists?` versus `S3-bucket-exists?`. I am open to changing the name if a better suggestion exists
=> Add `exists?` method to `S3Bucket` interface

doc/reference/gerbil/core/expression.md
This PR updates the documentation for the main imperative loop constructs provided by Gerbil: **do, do-while, while,** and **until.**
Each entry is organized into the following logical sections:
1.  **Signature:** The full technical signature of the form.
2.  **Summary:** A single, high-level sentence explaining its core purpose.
3.  **Description:** A detailed explanation of its behavior, arguments, return value, and edge cases.
4.  **Example(s):** Practical, self-contained examples demonstrating common use cases.
5.  **Context and Usage:** A crucial section explaining *why* and *when* to use this form compared to alternatives.
6.  **See Also:** Links to related forms to improve discoverability.
Note: English is not my native language (I’m a French speaker). The text was written with the …
=> Imperative loop expressions documentation

doc/reference/gerbil/core/control-flow.md, doc/reference/gerbil/core/expression.md
This PR continues the effort to create comprehensive, high-quality documentation for the Gerbil core macros.
The main changes include:
* **Improved Structure:** Renamed the old `expression.md` to `control-flow.md` and updated its title and introduction to more accurately reflect its scope (conditionals, logic, iteration, etc.).
* **New Comprehensive Docs:** Added complete documentation for the following forms:
* `begin0`
* `delay` and `delay-atomic`
* `@list`
* **Standardization:** Introduced badges (`R7RS`, `Gerbil`, etc.) to clearly distinguish the origin of each macro, as suggested by Fare. This pattern has been applied to all documented forms in this file.
=> docs: Improve and expand documentation for control flow macros
